In [1]:
import pandas as pd
from pathlib import Path

data_dir = Path("/Users/muhammadmuhdhar/Downloads/repo/nb-smith/tests/data/Credit Data")

# CSV files
Age_Bracket_Distribution = pd.read_csv(data_dir / "Age_Bracket_Distribution.csv")
Age_Income_Risk_Matrix = pd.read_csv(data_dir / "Age_Income_Risk_Matrix.csv")
Age_Risk_Summary = pd.read_csv(data_dir / "Age_Risk_Summary.csv")
Broken_Contract_Analysis = pd.read_csv(data_dir / "Broken_Contract_Analysis.csv")
Credit_Data___01_01_2025 = pd.read_csv(data_dir / "Credit Data - 01-01-2025.csv")
Credit_Data___30_03_2025 = pd.read_csv(data_dir / "Credit Data - 30-03-2025.csv")
Credit_Data___30_06_2025 = pd.read_csv(data_dir / "Credit Data - 30-06-2025.csv")
Credit_Data___30_09_2025 = pd.read_csv(data_dir / "Credit Data - 30-09-2025.csv")
Credit_Data___30_12_2025 = pd.read_csv(data_dir / "Credit Data - 30-12-2025.csv")
DPD_vs_NPS = pd.read_csv(data_dir / "DPD_vs_NPS.csv")
Income_Bracket_Distribution = pd.read_csv(data_dir / "Income_Bracket_Distribution.csv")
Monthly_Cure_Rates = pd.read_csv(data_dir / "Monthly_Cure_Rates.csv")
Portfolio_Summary = pd.read_csv(data_dir / "Portfolio_Summary.csv")
Vintage_Analysis_MOB12 = pd.read_csv(data_dir / "Vintage_Analysis_MOB12.csv")

# Excel files
Credit_Data_Definitions = pd.read_excel(data_dir / "Credit Data Definitions.xlsx", sheet_name="Credit Data Definitions")
NPS_Data = pd.read_excel(data_dir / "NPS Data.xlsx", sheet_name="Sheet1")
Sales_and_Customer_Data_Sales_Details = pd.read_excel(data_dir / "Sales and Customer Data.xlsx", sheet_name="Sales Details")
Sales_and_Customer_Data_Gender = pd.read_excel(data_dir / "Sales and Customer Data.xlsx", sheet_name="Gender")
Sales_and_Customer_Data_DOB = pd.read_excel(data_dir / "Sales and Customer Data.xlsx", sheet_name="DOB")
Sales_and_Customer_Data_Income_Level = pd.read_excel(data_dir / "Sales and Customer Data.xlsx", sheet_name="Income Level")

In [2]:
# Profile: Age_Bracket_Distribution
print("\n" + "="*60)
print("DataFrame: Age_Bracket_Distribution")
print("="*60)

# Shape
print(f"\nShape: {Age_Bracket_Distribution.shape[0]:,} rows, {Age_Bracket_Distribution.shape[1]:,} columns")

# Info
print("\n--- Info ---")
Age_Bracket_Distribution.info()

# Head
print("\n--- Head (5 rows) ---")
display(Age_Bracket_Distribution.head())

# Tail  
print("\n--- Tail (5 rows) ---")
display(Age_Bracket_Distribution.tail())

# Describe
print("\n--- Describe ---")
display(Age_Bracket_Distribution.describe(include='all'))

# Nulls
print("\n--- Null Values ---")
null_counts = Age_Bracket_Distribution.isnull().sum()
null_pct = (Age_Bracket_Distribution.isnull().sum() / len(Age_Bracket_Distribution)) * 100
null_df = pd.DataFrame({'Count': null_counts, 'Percentage': null_pct})
null_df = null_df[null_df['Count'] > 0].sort_values('Count', ascending=False)
if len(null_df) > 0:
    display(null_df)
else:
    print("No null values found")

# Uniques
print("\n--- Unique Values per Column ---")
unique_counts = Age_Bracket_Distribution.nunique().sort_values()
display(pd.DataFrame({'Unique': unique_counts}))

============================================================
DataFrame: Age_Bracket_Distribution
============================================================

Shape: 5 rows, 2 columns

--- Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age_brackets  5 non-null      object
 1   proportion    5 non-null      float64
dtypes: float64(1), object(1)
memory usage: 212.0+ bytes

--- Head (5 rows) ---

  age_brackets  proportion
0        26-35   53.857168
1        18-25   21.693216
2        36-45   17.791301
3        46-55    5.271165
4          55+    1.387149

--- Tail (5 rows) ---

  age_brackets  proportion
0        26-35   53.857168
1        18-25   21.693216
2        36-45   17.791301
3        46-55    5.271165
4          55+    1.387149

--- Describe ---

       age_brackets  proportion
count             5    5.000000
unique            5         NaN
top           26-35         NaN
freq              1         NaN
mean            NaN   20.000000
std             NaN   20.720943
min             NaN    1.387149
25%             NaN    5.271165
50%             NaN   17.791301
75%             NaN   21.693216
max             NaN   53.857168

--- Null Values ---
No null values found

--- Unique Values per Column ---

              Unique
age_brackets       5
proportion         5

In [3]:
# Profile: Age_Income_Risk_Matrix
print("\n" + "="*60)
print("DataFrame: Age_Income_Risk_Matrix")
print("="*60)

# Shape
print(f"\nShape: {Age_Income_Risk_Matrix.shape[0]:,} rows, {Age_Income_Risk_Matrix.shape[1]:,} columns")

# Info
print("\n--- Info ---")
Age_Income_Risk_Matrix.info()

# Head
print("\n--- Head (5 rows) ---")
display(Age_Income_Risk_Matrix.head())

# Tail  
print("\n--- Tail (5 rows) ---")
display(Age_Income_Risk_Matrix.tail())

# Describe
print("\n--- Describe ---")
display(Age_Income_Risk_Matrix.describe(include='all'))

# Nulls
print("\n--- Null Values ---")
null_counts = Age_Income_Risk_Matrix.isnull().sum()
null_pct = (Age_Income_Risk_Matrix.isnull().sum() / len(Age_Income_Risk_Matrix)) * 100
null_df = pd.DataFrame({'Count': null_counts, 'Percentage': null_pct})
null_df = null_df[null_df['Count'] > 0].sort_values('Count', ascending=False)
if len(null_df) > 0:
    display(null_df)
else:
    print("No null values found")

# Uniques
print("\n--- Unique Values per Column ---")
unique_counts = Age_Income_Risk_Matrix.nunique().sort_values()
display(pd.DataFrame({'Unique': unique_counts}))

============================================================
DataFrame: Age_Income_Risk_Matrix
============================================================

Shape: 5 rows, 9 columns

--- Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age_brackets  5 non-null      object
 1   Below 5k      3 non-null      float64
 2   5k-10k        5 non-null      float64
 3   10k-20k       5 non-null      float64
 4   20k-30k       5 non-null      float64
 5   30k-50k       5 non-null      float64
 6   50k-100k      5 non-null      float64
 7   100k-150k     5 non-null      float64
 8   150k+         5 non-null      float64
dtypes: float64(8), object(1)
memory usage: 492.0+ bytes

--- Head (5 rows) ---

,age_brackets,Below 5k,5k-10k,10k-20k,20k-30k,30k-50k,50k-100k,100k-150k,150k+
0,18-25,0.000000,39.130435,39.200000,41.395349,35.564854,31.221719,30.944625,28.162291
1,26-35,35.714286,34.090909,36.885246,34.634146,37.248322,29.653505,26.620370,25.878320
2,36-45,28.571429,0.000000,20.000000,23.529412,32.727273,27.573529,25.663717,23.566308
3,46-55,NaN,0.000000,15.384615,33.333333,41.666667,26.582278,25.352113,19.426752
4,55+,NaN,0.000000,50.000000,0.000000,44.444444,33.333333,46.153846,20.270270

--- Tail (5 rows) ---

,age_brackets,Below 5k,5k-10k,10k-20k,20k-30k,30k-50k,50k-100k,100k-150k,150k+
0,18-25,0.000000,39.130435,39.200000,41.395349,35.564854,31.221719,30.944625,28.162291
1,26-35,35.714286,34.090909,36.885246,34.634146,37.248322,29.653505,26.620370,25.878320
2,36-45,28.571429,0.000000,20.000000,23.529412,32.727273,27.573529,25.663717,23.566308
3,46-55,NaN,0.000000,15.384615,33.333333,41.666667,26.582278,25.352113,19.426752
4,55+,NaN,0.000000,50.000000,0.000000,44.444444,33.333333,46.153846,20.270270

--- Describe ---

,age_brackets,Below 5k,5k-10k,10k-20k,20k-30k,30k-50k,50k-100k,100k-150k,150k+
count,5,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
unique,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,18-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,21.428571,14.644269,32.293972,26.578448,38.330312,29.672873,30.946934,23.460788
std,NaN,18.898224,20.131493,14.312097,16.169213,4.709734,2.727512,8.791811,3.688244
min,NaN,0.000000,0.000000,15.384615,0.000000,32.727273,26.582278,25.352113,19.426752
25%,NaN,14.285714,0.000000,20.000000,23.529412,35.564854,27.573529,25.663717,20.270270
50%,NaN,28.571429,0.000000,36.885246,33.333333,37.248322,29.653505,26.620370,23.566308
75%,NaN,32.142857,34.090909,39.200000,34.634146,41.666667,31.221719,30.944625,25.878320
max,NaN,35.714286,39.130435,50.000000,41.395349,44.444444,33.333333,46.153846,28.162291

--- Null Values ---

          Count  Percentage
Below 5k      2        40.0

--- Unique Values per Column ---

              Unique
Below 5k           3
5k-10k             3
age_brackets       5
10k-20k            5
20k-30k            5
30k-50k            5
50k-100k           5
100k-150k          5
150k+              5

In [4]:
# Profile: Age_Risk_Summary
print("\n" + "="*60)
print("DataFrame: Age_Risk_Summary")
print("="*60)

# Shape
print(f"\nShape: {Age_Risk_Summary.shape[0]:,} rows, {Age_Risk_Summary.shape[1]:,} columns")

# Info
print("\n--- Info ---")
Age_Risk_Summary.info()

# Head
print("\n--- Head (5 rows) ---")
display(Age_Risk_Summary.head())

# Tail  
print("\n--- Tail (5 rows) ---")
display(Age_Risk_Summary.tail())

# Describe
print("\n--- Describe ---")
display(Age_Risk_Summary.describe(include='all'))

# Nulls
print("\n--- Null Values ---")
null_counts = Age_Risk_Summary.isnull().sum()
null_pct = (Age_Risk_Summary.isnull().sum() / len(Age_Risk_Summary)) * 100
null_df = pd.DataFrame({'Count': null_counts, 'Percentage': null_pct})
null_df = null_df[null_df['Count'] > 0].sort_values('Count', ascending=False)
if len(null_df) > 0:
    display(null_df)
else:
    print("No null values found")

# Uniques
print("\n--- Unique Values per Column ---")
unique_counts = Age_Risk_Summary.nunique().sort_values()
display(pd.DataFrame({'Unique': unique_counts}))

============================================================
DataFrame: Age_Risk_Summary
============================================================

Shape: 5 rows, 8 columns

--- Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   age_brackets          5 non-null      object
 1   is_par_30             5 non-null      float64
 2   is_par_90             5 non-null      float64
 3   WEEKLY_RATE           5 non-null      float64
 4   LOAN_ID               5 non-null      int64
 5   Share_of_Total_PAR30  5 non-null      float64
 6   is_par_90%            5 non-null      float64
 7   share_of_par_30%      5 non-null      float64
dtypes: float64(6), int64(1), object(1)
memory usage: 452.0+ bytes

--- Head (5 rows) ---

,age_brackets,is_par_30,is_par_90,WEEKLY_RATE,LOAN_ID,Share_of_Total_PAR30,is_par_90%,share_of_par_30%
0,18-25,0.329620,0.235561,1125.028878,2424,0.101409,23.56,10.14
1,26-35,0.295613,0.212529,1248.087087,6018,0.225790,21.25,22.58
2,36-45,0.255030,0.174547,1286.574447,1988,0.064348,17.45,6.43
3,46-55,0.227504,0.146010,1261.307301,589,0.017007,14.60,1.70
4,55+,0.270968,0.187097,1176.129032,155,0.005331,18.71,0.53

--- Tail (5 rows) ---

,age_brackets,is_par_30,is_par_90,WEEKLY_RATE,LOAN_ID,Share_of_Total_PAR30,is_par_90%,share_of_par_30%
0,18-25,0.329620,0.235561,1125.028878,2424,0.101409,23.56,10.14
1,26-35,0.295613,0.212529,1248.087087,6018,0.225790,21.25,22.58
2,36-45,0.255030,0.174547,1286.574447,1988,0.064348,17.45,6.43
3,46-55,0.227504,0.146010,1261.307301,589,0.017007,14.60,1.70
4,55+,0.270968,0.187097,1176.129032,155,0.005331,18.71,0.53

--- Describe ---

,age_brackets,is_par_30,is_par_90,WEEKLY_RATE,LOAN_ID,Share_of_Total_PAR30,is_par_90%,share_of_par_30%
count,5,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
unique,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,18-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,0.275747,0.191149,1219.425349,2234.800000,0.082777,19.114000,8.276000
std,NaN,0.038976,0.034493,66.839096,2315.358223,0.088689,3.451004,8.870329
min,NaN,0.227504,0.146010,1125.028878,155.000000,0.005331,14.600000,0.530000
25%,NaN,0.255030,0.174547,1176.129032,589.000000,0.017007,17.450000,1.700000
50%,NaN,0.270968,0.187097,1248.087087,1988.000000,0.064348,18.710000,6.430000
75%,NaN,0.295613,0.212529,1261.307301,2424.000000,0.101409,21.250000,10.140000
max,NaN,0.329620,0.235561,1286.574447,6018.000000,0.225790,23.560000,22.580000

--- Null Values ---
No null values found

--- Unique Values per Column ---

                      Unique
age_brackets               5
is_par_30                  5
is_par_90                  5
WEEKLY_RATE                5
LOAN_ID                    5
Share_of_Total_PAR30       5
is_par_90%                 5
share_of_par_30%           5

In [5]:
# Profile: Broken_Contract_Analysis
print("\n" + "="*60)
print("DataFrame: Broken_Contract_Analysis")
print("="*60)

# Shape
print(f"\nShape: {Broken_Contract_Analysis.shape[0]:,} rows, {Broken_Contract_Analysis.shape[1]:,} columns")

# Info
print("\n--- Info ---")
Broken_Contract_Analysis.info()

# Head
print("\n--- Head (5 rows) ---")
display(Broken_Contract_Analysis.head())

# Tail  
print("\n--- Tail (5 rows) ---")
display(Broken_Contract_Analysis.tail())

# Describe
print("\n--- Describe ---")
display(Broken_Contract_Analysis.describe(include='all'))

# Nulls
print("\n--- Null Values ---")
null_counts = Broken_Contract_Analysis.isnull().sum()
null_pct = (Broken_Contract_Analysis.isnull().sum() / len(Broken_Contract_Analysis)) * 100
null_df = pd.DataFrame({'Count': null_counts, 'Percentage': null_pct})
null_df = null_df[null_df['Count'] > 0].sort_values('Count', ascending=False)
if len(null_df) > 0:
    display(null_df)
else:
    print("No null values found")

# Uniques
print("\n--- Unique Values per Column ---")
unique_counts = Broken_Contract_Analysis.nunique().sort_values()
display(pd.DataFrame({'Unique': unique_counts}))

============================================================
DataFrame: Broken_Contract_Analysis
============================================================

Shape: 2 rows, 2 columns

--- Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Status     2 non-null      object
 1   NPS_Score  2 non-null      float64
dtypes: float64(1), object(1)
memory usage: 164.0+ bytes

--- Head (5 rows) ---

                        Status  NPS_Score
0          On-Time (No Issues)   7.479687
1  On-Time (System Lock Error)   6.225191

--- Tail (5 rows) ---

                        Status  NPS_Score
0          On-Time (No Issues)   7.479687
1  On-Time (System Lock Error)   6.225191

--- Describe ---

                     Status  NPS_Score
count                     2   2.000000
unique                    2        NaN
top     On-Time (No Issues)        NaN
freq                      1        NaN
mean                    NaN   6.852439
std                     NaN   0.887063
min                     NaN   6.225191
25%                     NaN   6.538815
50%                     NaN   6.852439
75%                     NaN   7.166063
max                     NaN   7.479687

--- Null Values ---
No null values found

--- Unique Values per Column ---

           Unique
Status          2
NPS_Score       2

In [6]:
# Profile: Credit_Data___01_01_2025
print("\n" + "="*60)
print("DataFrame: Credit_Data___01_01_2025")
print("="*60)

# Shape
print(f"\nShape: {Credit_Data___01_01_2025.shape[0]:,} rows, {Credit_Data___01_01_2025.shape[1]:,} columns")

# Info
print("\n--- Info ---")
Credit_Data___01_01_2025.info()

# Head
print("\n--- Head (5 rows) ---")
display(Credit_Data___01_01_2025.head())

# Tail  
print("\n--- Tail (5 rows) ---")
display(Credit_Data___01_01_2025.tail())

# Describe
print("\n--- Describe ---")
display(Credit_Data___01_01_2025.describe(include='all'))

# Nulls
print("\n--- Null Values ---")
null_counts = Credit_Data___01_01_2025.isnull().sum()
null_pct = (Credit_Data___01_01_2025.isnull().sum() / len(Credit_Data___01_01_2025)) * 100
null_df = pd.DataFrame({'Count': null_counts, 'Percentage': null_pct})
null_df = null_df[null_df['Count'] > 0].sort_values('Count', ascending=False)
if len(null_df) > 0:
    display(null_df)
else:
    print("No null values found")

# Uniques
print("\n--- Unique Values per Column ---")
unique_counts = Credit_Data___01_01_2025.nunique().sort_values()
display(pd.DataFrame({'Unique': unique_counts}))

============================================================
DataFrame: Credit_Data___01_01_2025
============================================================

Shape: 8,935 rows, 33 columns

--- Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8935 entries, 0 to 8934
Data columns (total 33 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   LOAN_ID                          8935 non-null   object
 1   DATE                             8935 non-null   object
 2   CUSTOMER_AGE                     8935 non-null   int64
 3   TOTAL_PAID                       8935 non-null   int64
 4   TOTAL_DUE_TODAY                  8930 non-null   float64
 5   BALANCE                          8934 non-null   float64
 6   DAYS_PAST_DUE                    8935 non-null   int64
 7   CLOSING_BALANCE                  8934 non-null   float64
 8   ADVANCE                          8935 non-null   int64
 9   BALANCE_DUE_TO_DATE              8930 non-null   float64
 10  ARREARS                          8935 non-null   int64
 11  BALANCE_DUE_STATUS               8935 non-null   object
 12  PAYMENT                          8935 non-null   int64
 13  EXPECTED_PAYMENT                 8934 non-null   float64
 14  FIRST_PAYMENT                    8935 non-null   int64
 15  FIRST_EXPECTED_PAYMENT           8935 non-null   int64
 16  ACCOUNT_STATUS_L1                8935 non-null   object
 17  ACCOUNT_STATUS_L2                8935 non-null   object
 18  RETURN_DATE                      986 non-null    object
 19  SALE_DATE                        8935 non-null   object
 20  CREDIT_CHECK_DONE                8935 non-null   object
 21  PAYMENT_AMOUNT                   570 non-null    float64
 22  ADJUSTMENT_AMOUNT                570 non-null    float64
 23  PREPAYMENT_AMOUNT                8935 non-null   int64
 24  DEPOSIT                          8934 non-null   float64
 25  WEEKLY_RATE                      8934 non-null   float64
 26  CREDIT_EXPIRY                    8935 non-null   object
 27  NEXT_INVOICE_DATE                8935 non-null   object
 28  DISCOUNT                         8935 non-null   int64
 29  OVERPAYMENT_AMOUNT               8935 non-null   int64
 30  MAX_PAYMENT_DATE                 8906 non-null   object
 31  INITIAL_PAY                      8935 non-null   int64
 32  TOTAL_PAID_WITH_ADJUSTMENTS_15D  8935 non-null   int64
dtypes: float64(9), int64(13), object(11)
memory usage: 2.2+ MB

--- Head (5 rows) ---

,LOAN_ID,DATE,CUSTOMER_AGE,TOTAL_PAID,TOTAL_DUE_TODAY,BALANCE,DAYS_PAST_DUE,CLOSING_BALANCE,ADVANCE,BALANCE_DUE_TO_DATE,...,PREPAYMENT_AMOUNT,DEPOSIT,WEEKLY_RATE,CREDIT_EXPIRY,NEXT_INVOICE_DATE,DISCOUNT,OVERPAYMENT_AMOUNT,MAX_PAYMENT_DATE,INITIAL_PAY,TOTAL_PAID_WITH_ADJUSTMENTS_15D
0,recnBZuKLsWCIm3cW,1/1/2025,102,20639,21649.0,38380.0,4,38380.0,0,-1010.0,...,0,6499.0,1010.0,12/28/2024,1/4/2025,0,0,1/7/2025,7509,20639
1,recwUTOdXSW5kSAed,1/1/2025,211,48101,49419.0,29038.0,0,0.0,0,-1318.0,...,0,8499.0,1320.0,12/31/2024,1/7/2025,0,0,10/10/2025,9819,48101
2,recPCzNo2d9qK1VB3,1/1/2025,22,52999,52999.0,0.0,0,0.0,0,0.0,...,0,13699.0,1580.0,12/17/2024,1/7/2025,0,0,12/10/2024,52999,52999
3,rec98Vut24ajzNeWL,1/1/2025,145,21899,48249.0,80600.0,110,80600.0,0,-26350.0,...,0,11499.0,1750.0,9/13/2024,1/3/2025,0,0,9/17/2024,13249,21899
4,recEmhLuKhmOsEqGl,1/1/2025,271,35719,35419.0,9840.0,0,0.0,300,300.0,...,0,4999.0,780.0,1/3/2025,1/3/2025,0,0,4/4/2025,5779,35719

--- Tail (5 rows) ---

,LOAN_ID,DATE,CUSTOMER_AGE,TOTAL_PAID,TOTAL_DUE_TODAY,BALANCE,DAYS_PAST_DUE,CLOSING_BALANCE,ADVANCE,BALANCE_DUE_TO_DATE,...,PREPAYMENT_AMOUNT,DEPOSIT,WEEKLY_RATE,CREDIT_EXPIRY,NEXT_INVOICE_DATE,DISCOUNT,OVERPAYMENT_AMOUNT,MAX_PAYMENT_DATE,INITIAL_PAY,TOTAL_PAID_WITH_ADJUSTMENTS_15D
8930,rec3LuWdTC6uK69U4,1/1/2025,182,9879,45759.0,70380.0,175,70380.0,0,-35880.0,...,0,8499.0,1380.0,7/10/2024,1/8/2025,0,0,7/3/2024,9879,9879
8931,rec3slhC3IfX7pMtz,1/1/2025,119,13869,45659.0,95370.0,112,95370.0,0,-31790.0,...,0,11999.0,1870.0,9/11/2024,1/8/2025,0,0,9/4/2024,13869,13869
8932,rec4VwIWJpZwEKkCP,1/1/2025,333,65699,65699.0,4600.0,0,0.0,0,0.0,...,0,10499.0,1150.0,1/4/2025,1/4/2025,0,0,1/7/2025,11649,65699
8933,recc8HL177Glugqjb,1/1/2025,93,13679,13679.0,25460.0,0,0.0,0,0.0,...,0,4299.0,670.0,1/6/2025,1/6/2025,0,0,9/18/2025,4969,13679
8934,rec3HbNB02LLGyy81,1/1/2025,175,23379,23479.0,19080.0,0,0.0,0,-100.0,...,0,4499.0,730.0,1/1/2025,1/8/2025,0,0,6/30/2025,5229,23379

--- Describe ---

,LOAN_ID,DATE,CUSTOMER_AGE,TOTAL_PAID,TOTAL_DUE_TODAY,BALANCE,DAYS_PAST_DUE,CLOSING_BALANCE,ADVANCE,BALANCE_DUE_TO_DATE,...,PREPAYMENT_AMOUNT,DEPOSIT,WEEKLY_RATE,CREDIT_EXPIRY,NEXT_INVOICE_DATE,DISCOUNT,OVERPAYMENT_AMOUNT,MAX_PAYMENT_DATE,INITIAL_PAY,TOTAL_PAID_WITH_ADJUSTMENTS_15D
count,8935,8935,8935.000000,8935.000000,8930.000000,8934.000000,8935.000000,8934.000000,8935.000000,8930.000000,...,8935.000000,8934.000000,8934.000000,8935,8935,8935.000000,8935.000000,8906,8935.000000,8935.000000
unique,8935,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,645,7,NaN,NaN,908,NaN,NaN
top,recnBZuKLsWCIm3cW,1/1/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1/4/2025,1/3/2025,NaN,NaN,8/30/2024,NaN,NaN
freq,1,8935,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,385,1550,NaN,NaN,119,NaN,NaN
mean,NaN,NaN,215.703302,32004.502742,42511.612318,38290.496082,71.905204,25816.156145,466.355008,-10554.239194,...,42.332289,8916.635997,1210.617864,NaN,NaN,168.901399,24.909569,NaN,11562.151539,31966.157583
std,NaN,NaN,151.317555,23004.184984,24680.035689,28168.828122,122.405584,30857.878193,2612.088739,18223.431873,...,1293.508126,5104.266975,480.511825,NaN,NaN,1865.170437,577.546915,NaN,9141.948617,23150.625060
min,NaN,NaN,1.000000,-20499.000000,3179.000000,-17870.000000,0.000000,-1.000000,0.000000,-168350.000000,...,0.000000,-1.000000,370.000000,NaN,NaN,0.000000,0.000000,NaN,-2261.000000,-20499.000000
25%,NaN,NaN,91.500000,13859.500000,24399.000000,18705.500000,0.000000,0.000000,0.000000,-18675.750000,...,0.000000,5499.000000,800.000000,NaN,NaN,0.000000,0.000000,NaN,6379.000000,13894.000000
50%,NaN,NaN,186.000000,26479.000000,40239.000000,36089.500000,0.000000,15700.000000,0.000000,-100.000000,...,0.000000,7999.000000,1160.000000,NaN,NaN,0.000000,0.000000,NaN,9189.000000,26709.000000
75%,NaN,NaN,314.000000,44379.000000,55719.000000,55120.000000,111.000000,44672.500000,0.000000,0.000000,...,0.000000,10499.000000,1410.000000,NaN,NaN,0.000000,0.000000,NaN,12369.000000,44379.000000
max,NaN,NaN,693.000000,222159.000000,334219.000000,205019.000000,685.000000,205019.000000,58771.000000,58771.000000,...,67049.000000,55499.000000,5360.000000,NaN,NaN,49240.000000,40600.000000,NaN,131999.000000,222159.000000

--- Null Values ---

                     Count  Percentage
PAYMENT_AMOUNT        8365   93.620593
ADJUSTMENT_AMOUNT     8365   93.620593
RETURN_DATE           7949   88.964745
MAX_PAYMENT_DATE        29    0.324566
TOTAL_DUE_TODAY          5    0.055960
BALANCE_DUE_TO_DATE      5    0.055960
BALANCE                  1    0.011192
CLOSING_BALANCE          1    0.011192
EXPECTED_PAYMENT         1    0.011192
DEPOSIT                  1    0.011192
WEEKLY_RATE              1    0.011192

--- Unique Values per Column ---

                                 Unique
FIRST_PAYMENT                         1
DATE                                  1
FIRST_EXPECTED_PAYMENT                1
ADJUSTMENT_AMOUNT                     2
BALANCE_DUE_STATUS                    3
CREDIT_CHECK_DONE                     4
NEXT_INVOICE_DATE                     7
ACCOUNT_STATUS_L2                     9
PREPAYMENT_AMOUNT                    14
ACCOUNT_STATUS_L1                    20
OVERPAYMENT_AMOUNT                   98
DISCOUNT                            113
EXPECTED_PAYMENT                    146
DEPOSIT                             172
PAYMENT_AMOUNT                      193
PAYMENT                             194
WEEKLY_RATE                         218
RETURN_DATE                         380
DAYS_PAST_DUE                       516
CUSTOMER_AGE                        581
SALE_DATE                           581
INITIAL_PAY                         629
CREDIT_EXPIRY                       645
ADVANCE                             678
MAX_PAYMENT_DATE                    908
TOTAL_DUE_TODAY                    1515
ARREARS                            2702
CLOSING_BALANCE                    2831
BALANCE_DUE_TO_DATE                3379
BALANCE                            4026
TOTAL_PAID_WITH_ADJUSTMENTS_15D    4135
TOTAL_PAID                         4193
LOAN_ID                            8935

In [7]:
# Profile: Credit_Data___30_03_2025
print("\n" + "="*60)
print("DataFrame: Credit_Data___30_03_2025")
print("="*60)

# Shape
print(f"\nShape: {Credit_Data___30_03_2025.shape[0]:,} rows, {Credit_Data___30_03_2025.shape[1]:,} columns")

# Info
print("\n--- Info ---")
Credit_Data___30_03_2025.info()

# Head
print("\n--- Head (5 rows) ---")
display(Credit_Data___30_03_2025.head())

# Tail  
print("\n--- Tail (5 rows) ---")
display(Credit_Data___30_03_2025.tail())

# Describe
print("\n--- Describe ---")
display(Credit_Data___30_03_2025.describe(include='all'))

# Nulls
print("\n--- Null Values ---")
null_counts = Credit_Data___30_03_2025.isnull().sum()
null_pct = (Credit_Data___30_03_2025.isnull().sum() / len(Credit_Data___30_03_2025)) * 100
null_df = pd.DataFrame({'Count': null_counts, 'Percentage': null_pct})
null_df = null_df[null_df['Count'] > 0].sort_values('Count', ascending=False)
if len(null_df) > 0:
    display(null_df)
else:
    print("No null values found")

# Uniques
print("\n--- Unique Values per Column ---")
unique_counts = Credit_Data___30_03_2025.nunique().sort_values()
display(pd.DataFrame({'Unique': unique_counts}))

============================================================
DataFrame: Credit_Data___30_03_2025
============================================================

Shape: 11,024 rows, 33 columns

--- Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11024 entries, 0 to 11023
Data columns (total 33 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   LOAN_ID                          11024 non-null  object
 1   DATE                             11024 non-null  object
 2   CUSTOMER_AGE                     11024 non-null  int64
 3   TOTAL_PAID                       11024 non-null  int64
 4   TOTAL_DUE_TODAY                  11019 non-null  float64
 5   BALANCE                          11023 non-null  float64
 6   DAYS_PAST_DUE                    11024 non-null  int64
 7   CLOSING_BALANCE                  11023 non-null  float64
 8   ADVANCE                          11024 non-null  int64
 9   BALANCE_DUE_TO_DATE              11019 non-null  float64
 10  ARREARS                          11024 non-null  int64
 11  BALANCE_DUE_STATUS               11024 non-null  object
 12  PAYMENT                          11024 non-null  int64
 13  EXPECTED_PAYMENT                 11024 non-null  int64
 14  FIRST_PAYMENT                    11024 non-null  int64
 15  FIRST_EXPECTED_PAYMENT           11024 non-null  int64
 16  ACCOUNT_STATUS_L1                11024 non-null  object
 17  ACCOUNT_STATUS_L2                11024 non-null  object
 18  RETURN_DATE                      1185 non-null   object
 19  SALE_DATE                        11024 non-null  object
 20  CREDIT_CHECK_DONE                11024 non-null  object
 21  PAYMENT_AMOUNT                   647 non-null    float64
 22  ADJUSTMENT_AMOUNT                647 non-null    float64
 23  PREPAYMENT_AMOUNT                11024 non-null  int64
 24  DEPOSIT                          11023 non-null  float64
 25  WEEKLY_RATE                      11023 non-null  float64
 26  CREDIT_EXPIRY                    11024 non-null  object
 27  NEXT_INVOICE_DATE                11024 non-null  object
 28  DISCOUNT                         11024 non-null  int64
 29  OVERPAYMENT_AMOUNT               11024 non-null  int64
 30  MAX_PAYMENT_DATE                 10958 non-null  object
 31  INITIAL_PAY                      11024 non-null  int64
 32  TOTAL_PAID_WITH_ADJUSTMENTS_15D  11024 non-null  int64
dtypes: float64(8), int64(14), object(11)
memory usage: 2.8+ MB

--- Head (5 rows) ---

,LOAN_ID,DATE,CUSTOMER_AGE,TOTAL_PAID,TOTAL_DUE_TODAY,BALANCE,DAYS_PAST_DUE,CLOSING_BALANCE,ADVANCE,BALANCE_DUE_TO_DATE,...,PREPAYMENT_AMOUNT,DEPOSIT,WEEKLY_RATE,CREDIT_EXPIRY,NEXT_INVOICE_DATE,DISCOUNT,OVERPAYMENT_AMOUNT,MAX_PAYMENT_DATE,INITIAL_PAY,TOTAL_PAID_WITH_ADJUSTMENTS_15D
0,recshsSkaJzHP663H,3/31/2025,246,9900,58179.0,70359.0,239,70359.0,0,-48279.0,...,0,8499.0,1380.0,8/4/2024,4/6/2025,0,0,7/28/2024,9879,9900
1,rec3WeGAgR8E7ai5J,3/31/2025,233,65280,123479.0,107159.0,149,107159.0,0,-58199.0,...,0,30999.0,2720.0,11/2/2024,4/5/2025,0,0,1/24/2025,33719,65280
2,recAvwoRHSCytDGyv,3/31/2025,572,106999,106999.0,0.0,0,0.0,0,0.0,...,0,15999.0,1750.0,9/4/2024,4/2/2025,0,0,8/10/2024,17749,106999
3,recXY01XbbKZhLt42,3/31/2025,104,23399,23399.0,40700.0,0,40700.0,0,0.0,...,0,6899.0,1100.0,4/1/2025,4/1/2025,0,0,10/14/2025,7999,23399
4,reciFeQteqkuTsQnC,3/31/2025,285,35029,54239.0,31750.0,117,31750.0,0,-19210.0,...,0,7499.0,1140.0,12/4/2024,4/2/2025,0,0,12/4/2024,8639,35029

--- Tail (5 rows) ---

,LOAN_ID,DATE,CUSTOMER_AGE,TOTAL_PAID,TOTAL_DUE_TODAY,BALANCE,DAYS_PAST_DUE,CLOSING_BALANCE,ADVANCE,BALANCE_DUE_TO_DATE,...,PREPAYMENT_AMOUNT,DEPOSIT,WEEKLY_RATE,CREDIT_EXPIRY,NEXT_INVOICE_DATE,DISCOUNT,OVERPAYMENT_AMOUNT,MAX_PAYMENT_DATE,INITIAL_PAY,TOTAL_PAID_WITH_ADJUSTMENTS_15D
11019,rec073uULkAuo8WHd,3/31/2025,529,44479,44479.0,0.0,0,0.0,0,0.0,...,0,5999.0,740.0,10/17/2024,4/3/2025,0,0,8/10/2024,6739,44479
11020,recHv9vm8MRIoucaK,3/31/2025,465,57299,57399.0,0.0,0,0.0,0,-100.0,...,0,7999.0,950.0,12/13/2024,4/4/2025,100,0,12/20/2024,8949,57299
11021,recq1FuuNTWKCjUnt,3/31/2025,423,45539,45539.0,0.0,0,0.0,0,0.0,...,0,5499.0,770.0,1/31/2025,4/4/2025,0,0,1/21/2025,6269,45539
11022,recoCxWzNTQF7jgS4,3/31/2025,136,12909,36199.0,67130.0,115,67130.0,0,-23290.0,...,0,8799.0,1370.0,12/6/2024,4/4/2025,0,0,12/1/2024,10169,12909
11023,reczZiie22UfW6jzq,3/31/2025,167,37739,35919.0,31220.0,0,0.0,1820,1820.0,...,0,7599.0,1180.0,4/8/2025,4/1/2025,0,0,12/23/2025,8779,37739

--- Describe ---

,LOAN_ID,DATE,CUSTOMER_AGE,TOTAL_PAID,TOTAL_DUE_TODAY,BALANCE,DAYS_PAST_DUE,CLOSING_BALANCE,ADVANCE,BALANCE_DUE_TO_DATE,...,PREPAYMENT_AMOUNT,DEPOSIT,WEEKLY_RATE,CREDIT_EXPIRY,NEXT_INVOICE_DATE,DISCOUNT,OVERPAYMENT_AMOUNT,MAX_PAYMENT_DATE,INITIAL_PAY,TOTAL_PAID_WITH_ADJUSTMENTS_15D
count,11024,11024,11024.000000,11024.000000,11019.000000,11023.000000,11024.000000,11023.000000,11024.000000,11019.000000,...,11024.000000,11023.000000,11023.000000,11024,11024,11024.000000,11024.000000,10958,11024.000000,11024.00000
unique,11024,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,743,7,NaN,NaN,909,NaN,NaN
top,recshsSkaJzHP663H,3/31/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4/4/2025,4/4/2025,NaN,NaN,12/25/2025,NaN,NaN
freq,1,11024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,423,1917,NaN,NaN,162,NaN,NaN
mean,NaN,NaN,254.813951,34942.286466,47996.125692,36286.600054,90.456549,28878.587989,503.485305,-13008.312642,...,37.984216,9323.514198,1240.459947,NaN,NaN,231.342253,24.916546,NaN,12365.098422,34996.82402
std,NaN,NaN,171.255840,25229.346299,26925.480690,28870.640723,145.265656,31517.741414,2989.201939,21156.677590,...,1226.736382,5720.069519,527.561088,NaN,NaN,2309.750425,541.291498,NaN,10242.311891,25412.29687
min,NaN,NaN,0.000000,-20499.000000,3799.000000,-37844.000000,0.000000,-1.000000,0.000000,-179579.000000,...,0.000000,-1.000000,370.000000,NaN,NaN,0.000000,0.000000,NaN,-2261.000000,-20499.00000
25%,NaN,NaN,113.000000,15249.000000,28069.000000,13609.500000,0.000000,0.000000,0.000000,-22399.500000,...,0.000000,5519.000000,850.000000,NaN,NaN,0.000000,0.000000,NaN,6739.000000,15365.00000
50%,NaN,NaN,237.000000,28999.500000,44479.000000,34170.000000,0.000000,25312.000000,0.000000,-1220.000000,...,0.000000,7999.000000,1170.000000,NaN,NaN,0.000000,0.000000,NaN,9229.000000,29239.00000
75%,NaN,NaN,366.000000,47499.000000,63159.000000,53840.000000,153.000000,50490.000000,0.000000,0.000000,...,0.000000,10699.000000,1470.000000,NaN,NaN,0.000000,0.000000,NaN,12924.000000,47499.00000
max,NaN,NaN,782.000000,222159.000000,334219.000000,205019.000000,774.000000,205019.000000,67760.000000,67760.000000,...,67049.000000,55499.000000,8720.000000,NaN,NaN,51080.000000,40600.000000,NaN,131999.000000,222159.00000

--- Null Values ---

                     Count  Percentage
PAYMENT_AMOUNT       10377   94.130987
ADJUSTMENT_AMOUNT    10377   94.130987
RETURN_DATE           9839   89.250726
MAX_PAYMENT_DATE        66    0.598694
TOTAL_DUE_TODAY          5    0.045356
BALANCE_DUE_TO_DATE      5    0.045356
BALANCE                  1    0.009071
CLOSING_BALANCE          1    0.009071
DEPOSIT                  1    0.009071
WEEKLY_RATE              1    0.009071

--- Unique Values per Column ---

                                 Unique
DATE                                  1
FIRST_PAYMENT                         2
FIRST_EXPECTED_PAYMENT                2
BALANCE_DUE_STATUS                    3
ADJUSTMENT_AMOUNT                     4
CREDIT_CHECK_DONE                     4
NEXT_INVOICE_DATE                     7
ACCOUNT_STATUS_L2                     9
PREPAYMENT_AMOUNT                    15
ACCOUNT_STATUS_L1                    20
OVERPAYMENT_AMOUNT                  119
DISCOUNT                            165
EXPECTED_PAYMENT                    172
PAYMENT_AMOUNT                      216
PAYMENT                             219
WEEKLY_RATE                         245
DEPOSIT                             281
RETURN_DATE                         428
DAYS_PAST_DUE                       604
CUSTOMER_AGE                        670
SALE_DATE                           670
ADVANCE                             720
INITIAL_PAY                         742
CREDIT_EXPIRY                       743
MAX_PAYMENT_DATE                    909
TOTAL_DUE_TODAY                    1778
ARREARS                            3470
CLOSING_BALANCE                    3558
BALANCE_DUE_TO_DATE                4189
BALANCE                            4641
TOTAL_PAID_WITH_ADJUSTMENTS_15D    4935
TOTAL_PAID                         4988
LOAN_ID                           11024

In [8]:
# Profile: Credit_Data___30_06_2025
print("\n" + "="*60)
print("DataFrame: Credit_Data___30_06_2025")
print("="*60)

# Shape
print(f"\nShape: {Credit_Data___30_06_2025.shape[0]:,} rows, {Credit_Data___30_06_2025.shape[1]:,} columns")

# Info
print("\n--- Info ---")
Credit_Data___30_06_2025.info()

# Head
print("\n--- Head (5 rows) ---")
display(Credit_Data___30_06_2025.head())

# Tail  
print("\n--- Tail (5 rows) ---")
display(Credit_Data___30_06_2025.tail())

# Describe
print("\n--- Describe ---")
display(Credit_Data___30_06_2025.describe(include='all'))

# Nulls
print("\n--- Null Values ---")
null_counts = Credit_Data___30_06_2025.isnull().sum()
null_pct = (Credit_Data___30_06_2025.isnull().sum() / len(Credit_Data___30_06_2025)) * 100
null_df = pd.DataFrame({'Count': null_counts, 'Percentage': null_pct})
null_df = null_df[null_df['Count'] > 0].sort_values('Count', ascending=False)
if len(null_df) > 0:
    display(null_df)
else:
    print("No null values found")

# Uniques
print("\n--- Unique Values per Column ---")
unique_counts = Credit_Data___30_06_2025.nunique().sort_values()
display(pd.DataFrame({'Unique': unique_counts}))

============================================================
DataFrame: Credit_Data___30_06_2025
============================================================

Shape: 13,891 rows, 34 columns

--- Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13891 entries, 0 to 13890
Data columns (total 34 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   LOAN_ID                          13891 non-null  object
 1   DATE                             13891 non-null  object
 2   CUSTOMER_AGE                     13891 non-null  int64
 3   TOTAL_PAID                       13891 non-null  int64
 4   TOTAL_DUE_TODAY                  13885 non-null  float64
 5   BALANCE                          13889 non-null  float64
 6   DAYS_PAST_DUE                    13891 non-null  int64
 7   CLOSING_BALANCE                  13889 non-null  float64
 8   ADVANCE                          13891 non-null  float64
 9   BALANCE_DUE_TO_DATE              13885 non-null  float64
 10  ARREARS                          13891 non-null  float64
 11  BALANCE_DUE_STATUS               13891 non-null  object
 12  PAYMENT                          13891 non-null  int64
 13  EXPECTED_PAYMENT                 13891 non-null  int64
 14  FIRST_PAYMENT                    13891 non-null  int64
 15  FIRST_EXPECTED_PAYMENT           13891 non-null  int64
 16  ACCOUNT_STATUS_L1                13891 non-null  object
 17  ACCOUNT_STATUS_L2                13891 non-null  object
 18  RETURN_DATE                      1402 non-null   object
 19  SALE_DATE                        13891 non-null  object
 20  CREDIT_CHECK_DONE                13891 non-null  object
 21  PAYMENT_AMOUNT                   901 non-null    float64
 22  ADJUSTMENT_AMOUNT                901 non-null    float64
 23  PREPAYMENT_AMOUNT                13891 non-null  int64
 24  DEPOSIT                          13889 non-null  float64
 25  WEEKLY_RATE                      13889 non-null  float64
 26  CREDIT_EXPIRY                    13891 non-null  object
 27  NEXT_INVOICE_DATE                13891 non-null  object
 28  Unnamed: 28                      0 non-null      float64
 29  DISCOUNT                         13891 non-null  float64
 30  OVERPAYMENT_AMOUNT               13891 non-null  float64
 31  MAX_PAYMENT_DATE                 13748 non-null  object
 32  INITIAL_PAY                      13891 non-null  int64
 33  TOTAL_PAID_WITH_ADJUSTMENTS_15D  13891 non-null  int64
dtypes: float64(13), int64(10), object(11)
memory usage: 3.6+ MB

--- Head (5 rows) ---

,LOAN_ID,DATE,CUSTOMER_AGE,TOTAL_PAID,TOTAL_DUE_TODAY,BALANCE,DAYS_PAST_DUE,CLOSING_BALANCE,ADVANCE,BALANCE_DUE_TO_DATE,...,DEPOSIT,WEEKLY_RATE,CREDIT_EXPIRY,NEXT_INVOICE_DATE,Unnamed: 28,DISCOUNT,OVERPAYMENT_AMOUNT,MAX_PAYMENT_DATE,INITIAL_PAY,TOTAL_PAID_WITH_ADJUSTMENTS_15D
0,recgxIh7nskDFWc1U,6/30/2025,185,10989,49729.0,75990.0,178,75990.0,0.0,-38740.0,...,9499.0,1490.0,1/3/2025,7/4/2025,NaN,0.0,0.0,12/27/2024,10989,10989
1,reccLxNBI117jtR33,6/30/2025,31,2850,9099.0,41649.0,10,41649.0,0.0,-1699.0,...,4849.0,850.0,6/20/2025,7/4/2025,NaN,0.0,0.0,6/6/2025,5699,7400
2,receTWDq9HmRf3nhx,6/30/2025,490,46339,45559.0,0.0,0,0.0,780.0,780.0,...,4999.0,780.0,3/3/2025,7/7/2025,NaN,0.0,780.0,3/31/2025,5779,46339
3,reck5WUFMK0wfjCb0,6/30/2025,343,9309,60999.0,53850.0,329,53850.0,0.0,-51690.0,...,6999.0,1080.0,8/5/2024,7/7/2025,NaN,0.0,0.0,8/5/2024,8079,9309
4,recuyXvloXj188QMR,6/30/2025,293,61639,89339.0,45400.0,0,0.0,0.0,-27700.0,...,14999.0,1770.0,3/11/2025,7/1/2025,NaN,0.0,0.0,12/17/2025,16769,61639

--- Tail (5 rows) ---

,LOAN_ID,DATE,CUSTOMER_AGE,TOTAL_PAID,TOTAL_DUE_TODAY,BALANCE,DAYS_PAST_DUE,CLOSING_BALANCE,ADVANCE,BALANCE_DUE_TO_DATE,...,DEPOSIT,WEEKLY_RATE,CREDIT_EXPIRY,NEXT_INVOICE_DATE,Unnamed: 28,DISCOUNT,OVERPAYMENT_AMOUNT,MAX_PAYMENT_DATE,INITIAL_PAY,TOTAL_PAID_WITH_ADJUSTMENTS_15D
13886,rec8ELpUNLmmbWjZ6,6/30/2025,257,5639,29089.0,33500.0,243,33500.0,0.0,-23450.0,...,4299.0,670.0,10/30/2024,7/2/2025,NaN,0.0,0.0,10/25/2024,4969,5639
13887,recdVUGFNZvgW2Z0D,6/30/2025,60,35479,35479.0,63960.0,0,63960.0,0.0,0.0,...,14159.0,1640.0,7/3/2025,7/3/2025,NaN,0.0,0.0,12/29/2025,22359,35479
13888,rec2GfEc6xgLOFVvW,6/30/2025,270,12359,45009.0,45520.0,228,45520.0,0.0,-32650.0,...,6399.0,990.0,11/14/2024,7/3/2025,NaN,0.0,0.0,11/8/2024,7389,12359
13889,rec131zlSu6XGZfrZ,6/30/2025,529,15009,49179.0,34170.0,452,34170.0,0.0,-34170.0,...,5499.0,840.0,4/4/2024,7/3/2025,NaN,0.0,0.0,5/6/2024,6339,15009
13890,recY23xdnwQNQSrA4,6/30/2025,132,5569,16959.0,33500.0,118,33500.0,0.0,-11390.0,...,4229.0,670.0,3/4/2025,7/1/2025,NaN,0.0,0.0,3/3/2025,4899,5569

--- Describe ---

,LOAN_ID,DATE,CUSTOMER_AGE,TOTAL_PAID,TOTAL_DUE_TODAY,BALANCE,DAYS_PAST_DUE,CLOSING_BALANCE,ADVANCE,BALANCE_DUE_TO_DATE,...,DEPOSIT,WEEKLY_RATE,CREDIT_EXPIRY,NEXT_INVOICE_DATE,Unnamed: 28,DISCOUNT,OVERPAYMENT_AMOUNT,MAX_PAYMENT_DATE,INITIAL_PAY,TOTAL_PAID_WITH_ADJUSTMENTS_15D
count,13891,13891,13891.000000,13891.000000,13885.000000,13889.000000,13891.000000,13889.000000,13891.000000,13885.000000,...,13889.000000,13889.000000,13891,13891,0.0,13891.000000,13891.000000,13748,13891.000000,13891.000000
unique,13891,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,834,7,NaN,NaN,NaN,909,NaN,NaN
top,recgxIh7nskDFWc1U,6/30/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,7/4/2025,7/4/2025,NaN,NaN,NaN,12/27/2025,NaN,NaN
freq,1,13891,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,628,2442,NaN,NaN,NaN,364,NaN,NaN
mean,NaN,NaN,283.567634,36219.144626,50703.019273,34420.623256,104.446620,31165.189445,444.200072,-14248.847793,...,9343.290446,1239.284326,NaN,NaN,NaN,314.139587,26.287827,NaN,12531.126557,36458.170542
std,NaN,NaN,195.732736,27448.218569,30238.033126,28711.717822,167.217435,30380.210081,2556.359993,23547.724725,...,6005.960986,535.523271,NaN,NaN,NaN,2754.522895,583.123482,NaN,10396.673560,27690.131352
min,NaN,NaN,0.000000,-20499.000000,3499.000000,-59524.000000,0.000000,-1.000000,0.000000,-205019.000000,...,-1.000000,240.000000,NaN,NaN,NaN,0.000000,0.000000,NaN,-2261.000000,-20499.000000
25%,NaN,NaN,114.000000,14699.000000,28979.000000,8630.000000,0.000000,0.000000,0.000000,-24250.000000,...,5599.000000,850.000000,NaN,NaN,NaN,0.000000,0.000000,NaN,6739.000000,14839.000000
50%,NaN,NaN,261.000000,29499.000000,45559.000000,33440.000000,0.000000,31000.000000,0.000000,-730.000000,...,7779.000000,1160.000000,NaN,NaN,NaN,0.000000,0.000000,NaN,9259.000000,29999.000000
75%,NaN,NaN,418.000000,49099.000000,67819.000000,52020.000000,175.000000,51430.000000,0.000000,0.000000,...,10599.000000,1470.000000,NaN,NaN,NaN,0.000000,0.000000,NaN,13189.000000,49799.000000
max,NaN,NaN,873.000000,222159.000000,334219.000000,205019.000000,865.000000,205019.000000,59524.000000,59524.000000,...,55499.000000,9060.000000,NaN,NaN,NaN,75135.000000,40600.000000,NaN,131999.000000,222159.000000

--- Null Values ---

                     Count  Percentage
Unnamed: 28          13891  100.000000
PAYMENT_AMOUNT       12990   93.513786
ADJUSTMENT_AMOUNT    12990   93.513786
RETURN_DATE          12489   89.907134
MAX_PAYMENT_DATE       143    1.029444
TOTAL_DUE_TODAY          6    0.043193
BALANCE_DUE_TO_DATE      6    0.043193
BALANCE                  2    0.014398
CLOSING_BALANCE          2    0.014398
DEPOSIT                  2    0.014398
WEEKLY_RATE              2    0.014398

--- Unique Values per Column ---

                                 Unique
Unnamed: 28                           0
DATE                                  1
FIRST_EXPECTED_PAYMENT                2
FIRST_PAYMENT                         2
BALANCE_DUE_STATUS                    3
CREDIT_CHECK_DONE                     4
NEXT_INVOICE_DATE                     7
ADJUSTMENT_AMOUNT                     9
ACCOUNT_STATUS_L2                     9
ACCOUNT_STATUS_L1                    20
PREPAYMENT_AMOUNT                    21
OVERPAYMENT_AMOUNT                  159
EXPECTED_PAYMENT                    196
PAYMENT_AMOUNT                      253
PAYMENT                             259
DISCOUNT                            275
WEEKLY_RATE                         278
DEPOSIT                             388
RETURN_DATE                         479
DAYS_PAST_DUE                       697
SALE_DATE                           761
CUSTOMER_AGE                        761
ADVANCE                             827
CREDIT_EXPIRY                       834
INITIAL_PAY                         840
MAX_PAYMENT_DATE                    909
TOTAL_DUE_TODAY                    1974
ARREARS                            4139
CLOSING_BALANCE                    4404
BALANCE_DUE_TO_DATE                4965
BALANCE                            5209
TOTAL_PAID_WITH_ADJUSTMENTS_15D    5684
TOTAL_PAID                         5747
LOAN_ID                           13891

In [9]:
# Profile: Credit_Data___30_09_2025
print("\n" + "="*60)
print("DataFrame: Credit_Data___30_09_2025")
print("="*60)

# Shape
print(f"\nShape: {Credit_Data___30_09_2025.shape[0]:,} rows, {Credit_Data___30_09_2025.shape[1]:,} columns")

# Info
print("\n--- Info ---")
Credit_Data___30_09_2025.info()

# Head
print("\n--- Head (5 rows) ---")
display(Credit_Data___30_09_2025.head())

# Tail  
print("\n--- Tail (5 rows) ---")
display(Credit_Data___30_09_2025.tail())

# Describe
print("\n--- Describe ---")
display(Credit_Data___30_09_2025.describe(include='all'))

# Nulls
print("\n--- Null Values ---")
null_counts = Credit_Data___30_09_2025.isnull().sum()
null_pct = (Credit_Data___30_09_2025.isnull().sum() / len(Credit_Data___30_09_2025)) * 100
null_df = pd.DataFrame({'Count': null_counts, 'Percentage': null_pct})
null_df = null_df[null_df['Count'] > 0].sort_values('Count', ascending=False)
if len(null_df) > 0:
    display(null_df)
else:
    print("No null values found")

# Uniques
print("\n--- Unique Values per Column ---")
unique_counts = Credit_Data___30_09_2025.nunique().sort_values()
display(pd.DataFrame({'Unique': unique_counts}))

============================================================
DataFrame: Credit_Data___30_09_2025
============================================================

Shape: 16,864 rows, 34 columns

--- Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16864 entries, 0 to 16863
Data columns (total 34 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   LOAN_ID                          16864 non-null  object
 1   DATE                             16864 non-null  object
 2   CUSTOMER_AGE                     16864 non-null  int64
 3   TOTAL_PAID                       16864 non-null  int64
 4   TOTAL_DUE_TODAY                  16858 non-null  float64
 5   BALANCE                          16862 non-null  float64
 6   DAYS_PAST_DUE                    16864 non-null  int64
 7   CLOSING_BALANCE                  16862 non-null  float64
 8   ADVANCE                          16864 non-null  float64
 9   BALANCE_DUE_TO_DATE              16858 non-null  float64
 10  ARREARS                          16864 non-null  float64
 11  BALANCE_DUE_STATUS               16864 non-null  object
 12  PAYMENT                          16864 non-null  int64
 13  EXPECTED_PAYMENT                 16864 non-null  int64
 14  FIRST_PAYMENT                    16864 non-null  int64
 15  FIRST_EXPECTED_PAYMENT           16864 non-null  int64
 16  ACCOUNT_STATUS_L1                16864 non-null  object
 17  ACCOUNT_STATUS_L2                16864 non-null  object
 18  RETURN_DATE                      1569 non-null   object
 19  SALE_DATE                        16864 non-null  object
 20  CREDIT_CHECK_DONE                16864 non-null  object
 21  PAYMENT_AMOUNT                   1015 non-null   float64
 22  ADJUSTMENT_AMOUNT                1015 non-null   float64
 23  PREPAYMENT_AMOUNT                16864 non-null  int64
 24  DEPOSIT                          16862 non-null  float64
 25  WEEKLY_RATE                      16862 non-null  float64
 26  CREDIT_EXPIRY                    16864 non-null  object
 27  NEXT_INVOICE_DATE                16864 non-null  object
 28  Unnamed: 28                      0 non-null      float64
 29  DISCOUNT                         16864 non-null  float64
 30  OVERPAYMENT_AMOUNT               16864 non-null  float64
 31  MAX_PAYMENT_DATE                 16658 non-null  object
 32  INITIAL_PAY                      16864 non-null  int64
 33  TOTAL_PAID_WITH_ADJUSTMENTS_15D  16864 non-null  int64
dtypes: float64(13), int64(10), object(11)
memory usage: 4.4+ MB

--- Head (5 rows) ---

,LOAN_ID,DATE,CUSTOMER_AGE,TOTAL_PAID,TOTAL_DUE_TODAY,BALANCE,DAYS_PAST_DUE,CLOSING_BALANCE,ADVANCE,BALANCE_DUE_TO_DATE,...,DEPOSIT,WEEKLY_RATE,CREDIT_EXPIRY,NEXT_INVOICE_DATE,Unnamed: 28,DISCOUNT,OVERPAYMENT_AMOUNT,MAX_PAYMENT_DATE,INITIAL_PAY,TOTAL_PAID_WITH_ADJUSTMENTS_15D
0,recldxczz0ENgjBeu,9/30/2025,430,48342,80259.0,31917.0,234,31917.0,0.0,-31917.0,...,8499.0,1380.0,2/8/2025,10/4/2025,NaN,0.0,0.0,3/3/2025,9879,48342
1,recP9I1GQ2AOHIDjJ,9/30/2025,334,7979,46679.0,42140.0,313,42140.0,0.0,-38700.0,...,5399.0,860.0,11/21/2024,10/2/2025,NaN,0.0,0.0,11/16/2024,6259,7979
2,recIGmllKJb6onIVM,9/30/2025,164,33169,33169.0,30520.0,0,30520.0,0.0,0.0,...,7009.0,1090.0,10/4/2025,10/4/2025,NaN,0.0,0.0,12/20/2025,8099,33169
3,recLprxkwOExsKXBZ,9/30/2025,165,39499,39499.0,36400.0,0,36400.0,0.0,0.0,...,8299.0,1300.0,10/3/2025,10/3/2025,NaN,0.0,0.0,12/13/2025,9599,39499
4,recYkYaYhNNHQUU24,9/30/2025,355,58709,67779.0,10250.0,0,0.0,0.0,-9070.0,...,7599.0,1180.0,8/7/2025,10/2/2025,NaN,0.0,0.0,11/21/2025,8779,58709

--- Tail (5 rows) ---

,LOAN_ID,DATE,CUSTOMER_AGE,TOTAL_PAID,TOTAL_DUE_TODAY,BALANCE,DAYS_PAST_DUE,CLOSING_BALANCE,ADVANCE,BALANCE_DUE_TO_DATE,...,DEPOSIT,WEEKLY_RATE,CREDIT_EXPIRY,NEXT_INVOICE_DATE,Unnamed: 28,DISCOUNT,OVERPAYMENT_AMOUNT,MAX_PAYMENT_DATE,INITIAL_PAY,TOTAL_PAID_WITH_ADJUSTMENTS_15D
16859,rec4VwIWJpZwEKkCP,9/30/2025,605,70299,70299.0,0.0,0,0.0,0.0,0.0,...,10499.0,1150.0,2/1/2025,10/4/2025,NaN,0.0,0.0,1/7/2025,11649,70299
16860,recc8HL177Glugqjb,9/30/2025,365,39139,39139.0,0.0,0,0.0,0.0,0.0,...,4299.0,670.0,9/29/2025,10/6/2025,NaN,0.0,0.0,9/18/2025,4969,39139
16861,recTQ5bvmJj2HEbgf,9/30/2025,223,45649,42749.0,18100.0,0,0.0,2900.0,2900.0,...,9149.0,1050.0,10/15/2025,10/1/2025,NaN,0.0,0.0,12/24/2025,10199,45649
16862,rec3HbNB02LLGyy81,9/30/2025,447,42359,42459.0,0.0,0,0.0,0.0,-100.0,...,4499.0,730.0,7/2/2025,10/1/2025,NaN,100.0,0.0,6/30/2025,5229,42359
16863,recwXAQ2vpoCyxvOG,9/30/2025,183,27639,27599.0,15500.0,0,15500.0,40.0,40.0,...,4659.0,740.0,10/6/2025,10/6/2025,NaN,0.0,0.0,12/29/2025,8359,27639

--- Describe ---

,LOAN_ID,DATE,CUSTOMER_AGE,TOTAL_PAID,TOTAL_DUE_TODAY,BALANCE,DAYS_PAST_DUE,CLOSING_BALANCE,ADVANCE,BALANCE_DUE_TO_DATE,...,DEPOSIT,WEEKLY_RATE,CREDIT_EXPIRY,NEXT_INVOICE_DATE,Unnamed: 28,DISCOUNT,OVERPAYMENT_AMOUNT,MAX_PAYMENT_DATE,INITIAL_PAY,TOTAL_PAID_WITH_ADJUSTMENTS_15D
count,16864,16864,16864.000000,16864.000000,16858.000000,16862.000000,16864.000000,16862.000000,16864.000000,16858.000000,...,16862.000000,16862.000000,16864,16864,0.0,16864.000000,16864.000000,16658,16864.000000,16864.000000
unique,16864,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,943,7,NaN,NaN,NaN,909,NaN,NaN
top,recldxczz0ENgjBeu,9/30/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,10/3/2025,10/3/2025,NaN,NaN,NaN,12/29/2025,NaN,NaN
freq,1,16864,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,763,2936,NaN,NaN,NaN,602,NaN,NaN
mean,NaN,NaN,317.467327,37695.379625,52729.526231,32419.734480,119.211871,31375.836449,415.334345,-14706.871112,...,9515.401969,1226.432214,NaN,NaN,NaN,432.546869,25.595825,NaN,12668.523245,38025.391129
std,NaN,NaN,217.836932,28736.245459,31625.397179,28634.321867,190.228032,29165.481975,2395.305301,24584.283388,...,6609.544589,533.121949,NaN,NaN,NaN,3336.488215,545.591161,NaN,10657.875854,29157.549284
min,NaN,NaN,0.000000,-20499.000000,3299.000000,-81294.000000,0.000000,-1.000000,0.000000,-205019.000000,...,-1.000000,240.000000,NaN,NaN,NaN,0.000000,0.000000,NaN,-2261.000000,-20499.000000
25%,NaN,NaN,129.000000,15317.750000,29999.000000,3205.000000,0.000000,0.000000,0.000000,-25360.000000,...,5499.000000,850.000000,NaN,NaN,NaN,0.000000,0.000000,NaN,6739.000000,15419.000000
50%,NaN,NaN,291.000000,30799.000000,46079.000000,30360.000000,0.000000,29750.000000,0.000000,-100.000000,...,7699.000000,1160.000000,NaN,NaN,NaN,0.000000,0.000000,NaN,9259.000000,31199.000000
75%,NaN,NaN,470.000000,51004.000000,69974.000000,49350.000000,199.000000,49000.000000,0.000000,0.000000,...,10499.000000,1450.000000,NaN,NaN,NaN,0.000000,0.000000,NaN,13289.000000,51641.500000
max,NaN,NaN,965.000000,222159.000000,334219.000000,205019.000000,957.000000,205019.000000,81294.000000,81294.000000,...,55499.000000,9060.000000,NaN,NaN,NaN,75135.000000,40600.000000,NaN,131999.000000,222159.000000

--- Null Values ---

                     Count  Percentage
Unnamed: 28          16864  100.000000
PAYMENT_AMOUNT       15849   93.981262
ADJUSTMENT_AMOUNT    15849   93.981262
RETURN_DATE          15295   90.696157
MAX_PAYMENT_DATE       206    1.221537
TOTAL_DUE_TODAY          6    0.035579
BALANCE_DUE_TO_DATE      6    0.035579
BALANCE                  2    0.011860
CLOSING_BALANCE          2    0.011860
DEPOSIT                  2    0.011860
WEEKLY_RATE              2    0.011860

--- Unique Values per Column ---

                                 Unique
Unnamed: 28                           0
DATE                                  1
FIRST_EXPECTED_PAYMENT                2
FIRST_PAYMENT                         2
BALANCE_DUE_STATUS                    3
CREDIT_CHECK_DONE                     4
ADJUSTMENT_AMOUNT                     5
NEXT_INVOICE_DATE                     7
ACCOUNT_STATUS_L2                     9
ACCOUNT_STATUS_L1                    20
PREPAYMENT_AMOUNT                    22
OVERPAYMENT_AMOUNT                  192
EXPECTED_PAYMENT                    200
PAYMENT_AMOUNT                      269
PAYMENT                             272
WEEKLY_RATE                         284
DISCOUNT                            412
DEPOSIT                             477
RETURN_DATE                         504
DAYS_PAST_DUE                       789
SALE_DATE                           852
CUSTOMER_AGE                        852
ADVANCE                             894
INITIAL_PAY                         899
MAX_PAYMENT_DATE                    909
CREDIT_EXPIRY                       943
TOTAL_DUE_TODAY                    2188
ARREARS                            4686
CLOSING_BALANCE                    5227
BALANCE_DUE_TO_DATE                5579
BALANCE                            5691
TOTAL_PAID_WITH_ADJUSTMENTS_15D    6305
TOTAL_PAID                         6367
LOAN_ID                           16864

In [10]:
# Profile: Credit_Data___30_12_2025
print("\n" + "="*60)
print("DataFrame: Credit_Data___30_12_2025")
print("="*60)

# Shape
print(f"\nShape: {Credit_Data___30_12_2025.shape[0]:,} rows, {Credit_Data___30_12_2025.shape[1]:,} columns")

# Info
print("\n--- Info ---")
Credit_Data___30_12_2025.info()

# Head
print("\n--- Head (5 rows) ---")
display(Credit_Data___30_12_2025.head())

# Tail  
print("\n--- Tail (5 rows) ---")
display(Credit_Data___30_12_2025.tail())

# Describe
print("\n--- Describe ---")
display(Credit_Data___30_12_2025.describe(include='all'))

# Nulls
print("\n--- Null Values ---")
null_counts = Credit_Data___30_12_2025.isnull().sum()
null_pct = (Credit_Data___30_12_2025.isnull().sum() / len(Credit_Data___30_12_2025)) * 100
null_df = pd.DataFrame({'Count': null_counts, 'Percentage': null_pct})
null_df = null_df[null_df['Count'] > 0].sort_values('Count', ascending=False)
if len(null_df) > 0:
    display(null_df)
else:
    print("No null values found")

# Uniques
print("\n--- Unique Values per Column ---")
unique_counts = Credit_Data___30_12_2025.nunique().sort_values()
display(pd.DataFrame({'Unique': unique_counts}))

============================================================
DataFrame: Credit_Data___30_12_2025
============================================================

Shape: 20,742 rows, 34 columns

--- Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20742 entries, 0 to 20741
Data columns (total 34 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   LOAN_ID                          20742 non-null  object
 1   DATE                             20742 non-null  object
 2   CUSTOMER_AGE                     20742 non-null  int64
 3   TOTAL_PAID                       20742 non-null  int64
 4   TOTAL_DUE_TODAY                  20736 non-null  float64
 5   BALANCE                          20740 non-null  float64
 6   DAYS_PAST_DUE                    20742 non-null  int64
 7   CLOSING_BALANCE                  20740 non-null  float64
 8   ADVANCE                          20742 non-null  float64
 9   BALANCE_DUE_TO_DATE              20736 non-null  float64
 10  ARREARS                          20742 non-null  float64
 11  BALANCE_DUE_STATUS               20742 non-null  object
 12  PAYMENT                          20742 non-null  int64
 13  EXPECTED_PAYMENT                 20742 non-null  int64
 14  FIRST_PAYMENT                    20742 non-null  int64
 15  FIRST_EXPECTED_PAYMENT           20742 non-null  int64
 16  ACCOUNT_STATUS_L1                20742 non-null  object
 17  ACCOUNT_STATUS_L2                20742 non-null  object
 18  RETURN_DATE                      1744 non-null   object
 19  SALE_DATE                        20742 non-null  object
 20  CREDIT_CHECK_DONE                20742 non-null  object
 21  PAYMENT_AMOUNT                   30 non-null     float64
 22  ADJUSTMENT_AMOUNT                30 non-null     float64
 23  PREPAYMENT_AMOUNT                20742 non-null  int64
 24  DEPOSIT                          20740 non-null  float64
 25  WEEKLY_RATE                      20740 non-null  float64
 26  CREDIT_EXPIRY                    20742 non-null  object
 27  NEXT_INVOICE_DATE                20742 non-null  object
 28  Unnamed: 28                      0 non-null      float64
 29  DISCOUNT                         20742 non-null  float64
 30  OVERPAYMENT_AMOUNT               20742 non-null  float64
 31  MAX_PAYMENT_DATE                 20437 non-null  object
 32  INITIAL_PAY                      20742 non-null  int64
 33  TOTAL_PAID_WITH_ADJUSTMENTS_15D  20742 non-null  int64
dtypes: float64(13), int64(10), object(11)
memory usage: 5.4+ MB

--- Head (5 rows) ---

,LOAN_ID,DATE,CUSTOMER_AGE,TOTAL_PAID,TOTAL_DUE_TODAY,BALANCE,DAYS_PAST_DUE,CLOSING_BALANCE,ADVANCE,BALANCE_DUE_TO_DATE,...,DEPOSIT,WEEKLY_RATE,CREDIT_EXPIRY,NEXT_INVOICE_DATE,Unnamed: 28,DISCOUNT,OVERPAYMENT_AMOUNT,MAX_PAYMENT_DATE,INITIAL_PAY,TOTAL_PAID_WITH_ADJUSTMENTS_15D
0,reczZiie22UfW6jzq,12/30/2025,441,68959,68959.0,0.0,0,0.0,0.0,0.0,...,7599.0,1180.0,10/14/2025,1/6/2026,NaN,0.0,0.0,12/23/2025,8779,68959
1,recvDazucywbN0XCG,12/30/2025,130,11399,11399.0,14850.0,0,14850.0,0.0,0.0,...,2849.0,450.0,1/2/2026,1/2/2026,NaN,0.0,0.0,12/25/2025,3299,11399
2,recEc4UFc7rXjdNqc,12/30/2025,883,137280,151459.0,0.0,0,0.0,0.0,-14179.0,...,22499.0,2480.0,6/10/2024,1/5/2026,NaN,14179.0,0.0,1/28/2024,27459,137280
3,rec1a55A7ospM1pyY,12/30/2025,32,11679,11679.0,54990.0,0,54990.0,0.0,0.0,...,5829.0,1170.0,1/2/2026,1/2/2026,NaN,0.0,0.0,12/26/2025,6999,11679
4,recqDWHPzwZrSsJii,12/30/2025,513,44944,45039.0,0.0,0,0.0,0.0,-95.0,...,4999.0,770.0,7/27/2025,1/4/2026,NaN,95.0,0.0,7/27/2025,5769,44944

--- Tail (5 rows) ---

,LOAN_ID,DATE,CUSTOMER_AGE,TOTAL_PAID,TOTAL_DUE_TODAY,BALANCE,DAYS_PAST_DUE,CLOSING_BALANCE,ADVANCE,BALANCE_DUE_TO_DATE,...,DEPOSIT,WEEKLY_RATE,CREDIT_EXPIRY,NEXT_INVOICE_DATE,Unnamed: 28,DISCOUNT,OVERPAYMENT_AMOUNT,MAX_PAYMENT_DATE,INITIAL_PAY,TOTAL_PAID_WITH_ADJUSTMENTS_15D
20737,rec4H2RvBFRWlSk9q,12/30/2025,559,67719,67819.0,0.0,0,0.0,0.0,-100.0,...,7499.0,1160.0,6/11/2025,12/31/2025,NaN,100.0,0.0,6/11/2025,8659,67719
20738,recsvtOtntr1VoNeq,12/30/2025,320,91249,102399.0,10680.0,0,10680.0,0.0,0.0,...,20519.0,1780.0,1/1/2026,1/1/2026,NaN,0.0,0.0,12/27/2025,22299,102399
20739,recQct0fCRQ3fHuic,12/30/2025,633,48039,48139.0,0.0,0,0.0,0.0,-100.0,...,5499.0,820.0,3/29/2025,1/3/2026,NaN,100.0,0.0,2/13/2025,6319,48039
20740,recoxmEnGMtKFkdY4,12/30/2025,138,95314,93509.0,81710.0,0,81710.0,13970.0,13970.0,...,33709.0,2990.0,1/29/2026,1/1/2026,NaN,0.0,0.0,12/24/2025,36699,107479
20741,recJjdoOyoQyy6Tf3,12/30/2025,524,101479,101479.0,0.0,0,0.0,0.0,0.0,...,10999.0,1740.0,7/23/2025,12/31/2025,NaN,0.0,0.0,7/15/2025,12739,101479

--- Describe ---

,LOAN_ID,DATE,CUSTOMER_AGE,TOTAL_PAID,TOTAL_DUE_TODAY,BALANCE,DAYS_PAST_DUE,CLOSING_BALANCE,ADVANCE,BALANCE_DUE_TO_DATE,...,DEPOSIT,WEEKLY_RATE,CREDIT_EXPIRY,NEXT_INVOICE_DATE,Unnamed: 28,DISCOUNT,OVERPAYMENT_AMOUNT,MAX_PAYMENT_DATE,INITIAL_PAY,TOTAL_PAID_WITH_ADJUSTMENTS_15D
count,20742,20742,20742.000000,20742.000000,20736.000000,20740.000000,20742.000000,20740.000000,20742.000000,20736.000000,...,20740.000000,20740.000000,20742,20742,0.0,20742.000000,20742.000000,20437,20742.000000,20742.000000
unique,20742,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1049,7,NaN,NaN,NaN,909,NaN,NaN
top,reczZiie22UfW6jzq,12/30/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1/2/2026,1/2/2026,NaN,NaN,NaN,12/29/2025,NaN,NaN
freq,1,20742,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,865,3522,NaN,NaN,NaN,1069,NaN,NaN
mean,NaN,NaN,339.927490,38267.057854,52906.300405,32234.703867,128.211503,32234.747310,419.989480,-14264.944599,...,9742.443587,1238.044841,NaN,NaN,NaN,538.610520,29.797098,NaN,12745.293029,38643.401311
std,NaN,NaN,243.162647,29736.114105,32505.113304,29091.245662,210.413389,29091.196685,2737.465444,24477.992648,...,6979.852806,537.590163,NaN,NaN,NaN,3746.782844,807.347353,NaN,10771.083570,30282.595151
min,NaN,NaN,1.000000,-20499.000000,3099.000000,-1000.000000,0.000000,-1.000000,0.000000,-187939.000000,...,-1.000000,240.000000,NaN,NaN,NaN,0.000000,0.000000,NaN,-2261.000000,-20499.000000
25%,NaN,NaN,131.000000,15099.000000,29516.500000,0.000000,0.000000,0.000000,0.000000,-24000.000000,...,5499.000000,870.000000,NaN,NaN,NaN,0.000000,0.000000,NaN,6599.000000,15159.000000
50%,NaN,NaN,299.000000,31099.000000,46899.000000,29910.000000,0.000000,29910.000000,0.000000,-600.000000,...,7779.000000,1150.000000,NaN,NaN,NaN,0.000000,0.000000,NaN,9199.000000,31499.000000
75%,NaN,NaN,523.000000,51999.750000,70399.000000,50490.000000,203.000000,50490.000000,0.000000,0.000000,...,10499.000000,1410.000000,NaN,NaN,NaN,0.000000,0.000000,NaN,13249.000000,52899.000000
max,NaN,NaN,1056.000000,222159.000000,334219.000000,187939.000000,1048.000000,187939.000000,91254.000000,91254.000000,...,55499.000000,9060.000000,NaN,NaN,NaN,86870.000000,91254.000000,NaN,131999.000000,222159.000000

--- Null Values ---

                     Count  Percentage
Unnamed: 28          20742  100.000000
PAYMENT_AMOUNT       20712   99.855366
ADJUSTMENT_AMOUNT    20712   99.855366
RETURN_DATE          18998   91.591939
MAX_PAYMENT_DATE       305    1.470446
TOTAL_DUE_TODAY          6    0.028927
BALANCE_DUE_TO_DATE      6    0.028927
BALANCE                  2    0.009642
CLOSING_BALANCE          2    0.009642
DEPOSIT                  2    0.009642
WEEKLY_RATE              2    0.009642

--- Unique Values per Column ---

                                 Unique
Unnamed: 28                           0
FIRST_EXPECTED_PAYMENT                1
DATE                                  1
ADJUSTMENT_AMOUNT                     1
RETURN_DATE                           1
FIRST_PAYMENT                         1
BALANCE_DUE_STATUS                    3
CREDIT_CHECK_DONE                     4
NEXT_INVOICE_DATE                     7
ACCOUNT_STATUS_L2                     9
ACCOUNT_STATUS_L1                    20
PREPAYMENT_AMOUNT                    22
PAYMENT_AMOUNT                       24
PAYMENT                              25
EXPECTED_PAYMENT                    201
OVERPAYMENT_AMOUNT                  231
WEEKLY_RATE                         307
DISCOUNT                            584
DEPOSIT                             602
DAYS_PAST_DUE                       881
MAX_PAYMENT_DATE                    909
SALE_DATE                           939
CUSTOMER_AGE                        939
INITIAL_PAY                         947
ADVANCE                             957
CREDIT_EXPIRY                      1049
TOTAL_DUE_TODAY                    2365
ARREARS                            5210
CLOSING_BALANCE                    6138
BALANCE                            6140
BALANCE_DUE_TO_DATE                6166
TOTAL_PAID_WITH_ADJUSTMENTS_15D    6988
TOTAL_PAID                         7098
LOAN_ID                           20742

In [11]:
# Profile: DPD_vs_NPS
print("\n" + "="*60)
print("DataFrame: DPD_vs_NPS")
print("="*60)

# Shape
print(f"\nShape: {DPD_vs_NPS.shape[0]:,} rows, {DPD_vs_NPS.shape[1]:,} columns")

# Info
print("\n--- Info ---")
DPD_vs_NPS.info()

# Head
print("\n--- Head (5 rows) ---")
display(DPD_vs_NPS.head())

# Tail  
print("\n--- Tail (5 rows) ---")
display(DPD_vs_NPS.tail())

# Describe
print("\n--- Describe ---")
display(DPD_vs_NPS.describe(include='all'))

# Nulls
print("\n--- Null Values ---")
null_counts = DPD_vs_NPS.isnull().sum()
null_pct = (DPD_vs_NPS.isnull().sum() / len(DPD_vs_NPS)) * 100
null_df = pd.DataFrame({'Count': null_counts, 'Percentage': null_pct})
null_df = null_df[null_df['Count'] > 0].sort_values('Count', ascending=False)
if len(null_df) > 0:
    display(null_df)
else:
    print("No null values found")

# Uniques
print("\n--- Unique Values per Column ---")
unique_counts = DPD_vs_NPS.nunique().sort_values()
display(pd.DataFrame({'Unique': unique_counts}))

============================================================
DataFrame: DPD_vs_NPS
============================================================

Shape: 90 rows, 2 columns

--- Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   DAYS_PAST_DUE  90 non-null     int64
 1   NPS_Score      90 non-null     float64
dtypes: float64(1), int64(1)
memory usage: 1.5 KB

--- Head (5 rows) ---

   DAYS_PAST_DUE  NPS_Score
0              0   7.114835
1              1   7.059406
2              2   7.000000
3              3   6.794872
4              4   6.675676

--- Tail (5 rows) ---

    DAYS_PAST_DUE  NPS_Score
85             85   8.000000
86             87   9.666667
87             88   9.500000
88             89   7.500000
89             90   6.800000

--- Describe ---

       DAYS_PAST_DUE  NPS_Score
count      90.000000  90.000000
mean       44.544444   7.068158
std        26.199391   1.644792
min         0.000000   0.000000
25%        22.250000   6.285714
50%        44.500000   7.107417
75%        66.750000   8.000000
max        90.000000  10.000000

--- Null Values ---
No null values found

--- Unique Values per Column ---

               Unique
NPS_Score          55
DAYS_PAST_DUE      90

In [12]:
# Profile: Income_Bracket_Distribution
print("\n" + "="*60)
print("DataFrame: Income_Bracket_Distribution")
print("="*60)

# Shape
print(f"\nShape: {Income_Bracket_Distribution.shape[0]:,} rows, {Income_Bracket_Distribution.shape[1]:,} columns")

# Info
print("\n--- Info ---")
Income_Bracket_Distribution.info()

# Head
print("\n--- Head (5 rows) ---")
display(Income_Bracket_Distribution.head())

# Tail  
print("\n--- Tail (5 rows) ---")
display(Income_Bracket_Distribution.tail())

# Describe
print("\n--- Describe ---")
display(Income_Bracket_Distribution.describe(include='all'))

# Nulls
print("\n--- Null Values ---")
null_counts = Income_Bracket_Distribution.isnull().sum()
null_pct = (Income_Bracket_Distribution.isnull().sum() / len(Income_Bracket_Distribution)) * 100
null_df = pd.DataFrame({'Count': null_counts, 'Percentage': null_pct})
null_df = null_df[null_df['Count'] > 0].sort_values('Count', ascending=False)
if len(null_df) > 0:
    display(null_df)
else:
    print("No null values found")

# Uniques
print("\n--- Unique Values per Column ---")
unique_counts = Income_Bracket_Distribution.nunique().sort_values()
display(pd.DataFrame({'Unique': unique_counts}))

============================================================
DataFrame: Income_Bracket_Distribution
============================================================

Shape: 8 rows, 2 columns

--- Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   income_bracket  8 non-null      object
 1   proportion      8 non-null      float64
dtypes: float64(1), object(1)
memory usage: 260.0+ bytes

--- Head (5 rows) ---

  income_bracket  proportion
0          150k+   42.143463
1       50k-100k   22.650580
2      100k-150k   14.553681
3        30k-50k   12.065228
4        20k-30k    4.778961

--- Tail (5 rows) ---

  income_bracket  proportion
3        30k-50k   12.065228
4        20k-30k    4.778961
5        10k-20k    2.780658
6         5k-10k    0.735225
7       Below 5k    0.292205

--- Describe ---

       income_bracket  proportion
count               8    8.000000
unique              8         NaN
top             150k+         NaN
freq                1         NaN
mean              NaN   12.500000
std               NaN   14.281337
min               NaN    0.292205
25%               NaN    2.269300
50%               NaN    8.422094
75%               NaN   16.577906
max               NaN   42.143463

--- Null Values ---
No null values found

--- Unique Values per Column ---

                Unique
income_bracket       8
proportion           8

In [13]:
# Profile: Monthly_Cure_Rates
print("\n" + "="*60)
print("DataFrame: Monthly_Cure_Rates")
print("="*60)

# Shape
print(f"\nShape: {Monthly_Cure_Rates.shape[0]:,} rows, {Monthly_Cure_Rates.shape[1]:,} columns")

# Info
print("\n--- Info ---")
Monthly_Cure_Rates.info()

# Head
print("\n--- Head (5 rows) ---")
display(Monthly_Cure_Rates.head())

# Tail  
print("\n--- Tail (5 rows) ---")
display(Monthly_Cure_Rates.tail())

# Describe
print("\n--- Describe ---")
display(Monthly_Cure_Rates.describe(include='all'))

# Nulls
print("\n--- Null Values ---")
null_counts = Monthly_Cure_Rates.isnull().sum()
null_pct = (Monthly_Cure_Rates.isnull().sum() / len(Monthly_Cure_Rates)) * 100
null_df = pd.DataFrame({'Count': null_counts, 'Percentage': null_pct})
null_df = null_df[null_df['Count'] > 0].sort_values('Count', ascending=False)
if len(null_df) > 0:
    display(null_df)
else:
    print("No null values found")

# Uniques
print("\n--- Unique Values per Column ---")
unique_counts = Monthly_Cure_Rates.nunique().sort_values()
display(pd.DataFrame({'Unique': unique_counts}))

============================================================
DataFrame: Monthly_Cure_Rates
============================================================

Shape: 5 rows, 3 columns

--- Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Month            5 non-null      object
 1   Cure_Rate        5 non-null      float64
 2   Delinquent_Pool  5 non-null      int64
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes

--- Head (5 rows) ---

                 Month  Cure_Rate  Delinquent_Pool
0                  Mar   0.005573             3768
1                  Jun   0.014174             4868
2                  Sep   0.016901             6035
3                  Dec   0.019150             7415
4  Jan-Dec (Full Year)   0.000000             3768

--- Tail (5 rows) ---

                 Month  Cure_Rate  Delinquent_Pool
0                  Mar   0.005573             3768
1                  Jun   0.014174             4868
2                  Sep   0.016901             6035
3                  Dec   0.019150             7415
4  Jan-Dec (Full Year)   0.000000             3768

--- Describe ---

       Month  Cure_Rate  Delinquent_Pool
count      5   5.000000          5.00000
unique     5        NaN              NaN
top      Mar        NaN              NaN
freq       1        NaN              NaN
mean     NaN   0.011160       5170.80000
std      NaN   0.008088       1566.09856
min      NaN   0.000000       3768.00000
25%      NaN   0.005573       3768.00000
50%      NaN   0.014174       4868.00000
75%      NaN   0.016901       6035.00000
max      NaN   0.019150       7415.00000

--- Null Values ---
No null values found

--- Unique Values per Column ---

                 Unique
Delinquent_Pool       4
Month                 5
Cure_Rate             5

In [14]:
# Profile: Portfolio_Summary
print("\n" + "="*60)
print("DataFrame: Portfolio_Summary")
print("="*60)

# Shape
print(f"\nShape: {Portfolio_Summary.shape[0]:,} rows, {Portfolio_Summary.shape[1]:,} columns")

# Info
print("\n--- Info ---")
Portfolio_Summary.info()

# Head
print("\n--- Head (5 rows) ---")
display(Portfolio_Summary.head())

# Tail  
print("\n--- Tail (5 rows) ---")
display(Portfolio_Summary.tail())

# Describe
print("\n--- Describe ---")
display(Portfolio_Summary.describe(include='all'))

# Nulls
print("\n--- Null Values ---")
null_counts = Portfolio_Summary.isnull().sum()
null_pct = (Portfolio_Summary.isnull().sum() / len(Portfolio_Summary)) * 100
null_df = pd.DataFrame({'Count': null_counts, 'Percentage': null_pct})
null_df = null_df[null_df['Count'] > 0].sort_values('Count', ascending=False)
if len(null_df) > 0:
    display(null_df)
else:
    print("No null values found")

# Uniques
print("\n--- Unique Values per Column ---")
unique_counts = Portfolio_Summary.nunique().sort_values()
display(pd.DataFrame({'Unique': unique_counts}))

============================================================
DataFrame: Portfolio_Summary
============================================================

Shape: 5 rows, 12 columns

--- Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Month                    5 non-null      object
 1   Unique Loans             5 non-null      int64
 2   Total_Outstanding_Value  5 non-null      float64
 3   Total_Arrears            5 non-null      float64
 4   Volume_Growth_%          4 non-null      float64
 5   Value_Growth_%           4 non-null      float64
 6   Arrears_growth_%         4 non-null      float64
 7   Avg_Loan_Balance         5 non-null      float64
 8   Arrears_Ratio_%          5 non-null      float64
 9   Arrears_ratio_growth_%   4 non-null      float64
 10  Unique Loans_indexed     5 non-null      float64
 11  Total_Arrears_indexed    5 non-null      float64
dtypes: float64(10), int64(1), object(1)
memory usage: 612.0+ bytes

--- Head (5 rows) ---

,Month,Unique Loans,Total_Outstanding_Value,Total_Arrears,Volume_Growth_%,Value_Growth_%,Arrears_growth_%,Avg_Loan_Balance,Arrears_Ratio_%,Arrears_ratio_growth_%,Unique Loans_indexed,Total_Arrears_indexed
0,Jan,8935,230641539.0,98416238.0,NaN,NaN,NaN,25813.266816,42.670647,NaN,100.000000,100.000000
1,Mar,11024,318328675.4,148889019.0,23.379966,38.018796,51.285014,28875.968378,46.772104,9.611892,123.379966,151.285014
2,Jun,13891,432853316.2,204015634.8,26.006894,35.976853,37.025307,31160.702340,47.132742,0.771053,155.467264,207.298754
3,Sep,16864,529059354.2,254932631.6,21.402347,22.226014,24.957399,31372.115406,48.186017,2.234701,188.740907,259.035132
4,Dec,20742,668548659.2,304509313.0,22.995731,26.365530,19.446974,32231.639148,45.547816,-5.475035,232.143257,309.409625

--- Tail (5 rows) ---

,Month,Unique Loans,Total_Outstanding_Value,Total_Arrears,Volume_Growth_%,Value_Growth_%,Arrears_growth_%,Avg_Loan_Balance,Arrears_Ratio_%,Arrears_ratio_growth_%,Unique Loans_indexed,Total_Arrears_indexed
0,Jan,8935,230641539.0,98416238.0,NaN,NaN,NaN,25813.266816,42.670647,NaN,100.000000,100.000000
1,Mar,11024,318328675.4,148889019.0,23.379966,38.018796,51.285014,28875.968378,46.772104,9.611892,123.379966,151.285014
2,Jun,13891,432853316.2,204015634.8,26.006894,35.976853,37.025307,31160.702340,47.132742,0.771053,155.467264,207.298754
3,Sep,16864,529059354.2,254932631.6,21.402347,22.226014,24.957399,31372.115406,48.186017,2.234701,188.740907,259.035132
4,Dec,20742,668548659.2,304509313.0,22.995731,26.365530,19.446974,32231.639148,45.547816,-5.475035,232.143257,309.409625

--- Describe ---

,Month,Unique Loans,Total_Outstanding_Value,Total_Arrears,Volume_Growth_%,Value_Growth_%,Arrears_growth_%,Avg_Loan_Balance,Arrears_Ratio_%,Arrears_ratio_growth_%,Unique Loans_indexed,Total_Arrears_indexed
count,5,5.000000,5.000000e+00,5.000000e+00,4.000000,4.000000,4.000000,5.000000,5.000000,4.000000,5.000000,5.000000
unique,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Jan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,14291.200000,4.358863e+08,2.021526e+08,23.446234,30.646798,33.178673,29890.738417,46.061865,1.785653,159.946279,205.405705
std,NaN,4683.902081,1.723132e+08,8.195173e+07,1.909782,7.571761,14.127810,2595.314782,2.117064,6.196737,52.421959,83.270532
min,NaN,8935.000000,2.306415e+08,9.841624e+07,21.402347,22.226014,19.446974,25813.266816,42.670647,-5.475035,100.000000,100.000000
25%,NaN,11024.000000,3.183287e+08,1.488890e+08,22.597385,25.330651,23.579793,28875.968378,45.547816,-0.790469,123.379966,151.285014
50%,NaN,13891.000000,4.328533e+08,2.040156e+08,23.187848,31.171192,30.991353,31160.702340,46.772104,1.502877,155.467264,207.298754
75%,NaN,16864.000000,5.290594e+08,2.549326e+08,24.036698,36.487339,40.590233,31372.115406,47.132742,4.078998,188.740907,259.035132
max,NaN,20742.000000,6.685487e+08,3.045093e+08,26.006894,38.018796,51.285014,32231.639148,48.186017,9.611892,232.143257,309.409625

--- Null Values ---

                        Count  Percentage
Volume_Growth_%             1        20.0
Value_Growth_%              1        20.0
Arrears_growth_%            1        20.0
Arrears_ratio_growth_%      1        20.0

--- Unique Values per Column ---

                         Unique
Volume_Growth_%               4
Value_Growth_%                4
Arrears_growth_%              4
Arrears_ratio_growth_%        4
Month                         5
Unique Loans                  5
Total_Outstanding_Value       5
Total_Arrears                 5
Avg_Loan_Balance              5
Arrears_Ratio_%               5
Unique Loans_indexed          5
Total_Arrears_indexed         5

In [15]:
# Profile: Vintage_Analysis_MOB12
print("\n" + "="*60)
print("DataFrame: Vintage_Analysis_MOB12")
print("="*60)

# Shape
print(f"\nShape: {Vintage_Analysis_MOB12.shape[0]:,} rows, {Vintage_Analysis_MOB12.shape[1]:,} columns")

# Info
print("\n--- Info ---")
Vintage_Analysis_MOB12.info()

# Head
print("\n--- Head (5 rows) ---")
display(Vintage_Analysis_MOB12.head())

# Tail  
print("\n--- Tail (5 rows) ---")
display(Vintage_Analysis_MOB12.tail())

# Describe
print("\n--- Describe ---")
display(Vintage_Analysis_MOB12.describe(include='all'))

# Nulls
print("\n--- Null Values ---")
null_counts = Vintage_Analysis_MOB12.isnull().sum()
null_pct = (Vintage_Analysis_MOB12.isnull().sum() / len(Vintage_Analysis_MOB12)) * 100
null_df = pd.DataFrame({'Count': null_counts, 'Percentage': null_pct})
null_df = null_df[null_df['Count'] > 0].sort_values('Count', ascending=False)
if len(null_df) > 0:
    display(null_df)
else:
    print("No null values found")

# Uniques
print("\n--- Unique Values per Column ---")
unique_counts = Vintage_Analysis_MOB12.nunique().sort_values()
display(pd.DataFrame({'Unique': unique_counts}))

============================================================
DataFrame: Vintage_Analysis_MOB12
============================================================

Shape: 10 rows, 3 columns

--- Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Vintage  10 non-null     object
 1   PAR30    10 non-null     float64
 2   PAR90    10 non-null     float64
dtypes: float64(2), object(1)
memory usage: 372.0+ bytes

--- Head (5 rows) ---

   Vintage  PAR30  PAR90
0  2024-01  40.74  39.51
1  2024-02  44.09  38.18
2  2024-03  55.38  52.69
3  2024-04  54.21  51.84
4  2024-06  50.66  47.60

--- Tail (5 rows) ---

   Vintage  PAR30  PAR90
5  2024-07  49.92  47.60
6  2024-09  51.93  50.83
7  2024-10  52.85  50.37
8  2024-12  47.10  44.20
9  2025-01  48.95  43.72

--- Describe ---

        Vintage      PAR30      PAR90
count        10  10.000000  10.000000
unique       10        NaN        NaN
top     2024-01        NaN        NaN
freq          1        NaN        NaN
mean        NaN  49.583000  46.654000
std         NaN   4.563225   5.097289
min         NaN  40.740000  38.180000
25%         NaN  47.562500  43.840000
50%         NaN  50.290000  47.600000
75%         NaN  52.620000  50.715000
max         NaN  55.380000  52.690000

--- Null Values ---
No null values found

--- Unique Values per Column ---

         Unique
PAR90         9
Vintage      10
PAR30        10

In [16]:
# Profile: Credit_Data_Definitions
print("\n" + "="*60)
print("DataFrame: Credit_Data_Definitions")
print("="*60)

# Shape
print(f"\nShape: {Credit_Data_Definitions.shape[0]:,} rows, {Credit_Data_Definitions.shape[1]:,} columns")

# Info
print("\n--- Info ---")
Credit_Data_Definitions.info()

# Head
print("\n--- Head (5 rows) ---")
display(Credit_Data_Definitions.head())

# Tail  
print("\n--- Tail (5 rows) ---")
display(Credit_Data_Definitions.tail())

# Describe
print("\n--- Describe ---")
display(Credit_Data_Definitions.describe(include='all'))

# Nulls
print("\n--- Null Values ---")
null_counts = Credit_Data_Definitions.isnull().sum()
null_pct = (Credit_Data_Definitions.isnull().sum() / len(Credit_Data_Definitions)) * 100
null_df = pd.DataFrame({'Count': null_counts, 'Percentage': null_pct})
null_df = null_df[null_df['Count'] > 0].sort_values('Count', ascending=False)
if len(null_df) > 0:
    display(null_df)
else:
    print("No null values found")

# Uniques
print("\n--- Unique Values per Column ---")
unique_counts = Credit_Data_Definitions.nunique().sort_values()
display(pd.DataFrame({'Unique': unique_counts}))

============================================================
DataFrame: Credit_Data_Definitions
============================================================

Shape: 33 rows, 2 columns

--- Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Column Name  33 non-null     object
 1   Definition   33 non-null     object
dtypes: object(2)
memory usage: 660.0+ bytes

--- Head (5 rows) ---

       Column Name                                         Definition
0          LOAN_ID                    Unique identifier for the loan.
1             DATE  Reporting (snapshot) date on which all loan me...
2     CUSTOMER_AGE  Number of days since the loan sale date (SALE_...
3       TOTAL_PAID  Cumulative amount paid by the customer up to t...
4  TOTAL_DUE_TODAY  Total amount the customer is expected to have ...

--- Tail (5 rows) ---

,Column Name,Definition
28,DISCOUNT,Discount applied to the loan or cash price.
29,OVERPAYMENT_AMOUNT,Amount paid in excess of the total expected lo...
30,MAX_PAYMENT_DATE,Most recent date on which a payment was record...
31,INITIAL_PAY,"Initial payment made at the start of the loan,..."
32,TOTAL_PAID_WITH_ADJUSTMENTS_15D,Total payments plus adjustments made within th...

--- Describe ---

       Column Name                       Definition
count           33                               33
unique          33                               33
top        LOAN_ID  Unique identifier for the loan.
freq             1                                1

--- Null Values ---
No null values found

--- Unique Values per Column ---

             Unique
Column Name      33
Definition       33

In [17]:
# Profile: NPS_Data
print("\n" + "="*60)
print("DataFrame: NPS_Data")
print("="*60)

# Shape
print(f"\nShape: {NPS_Data.shape[0]:,} rows, {NPS_Data.shape[1]:,} columns")

# Info
print("\n--- Info ---")
NPS_Data.info()

# Head
print("\n--- Head (5 rows) ---")
display(NPS_Data.head())

# Tail  
print("\n--- Tail (5 rows) ---")
display(NPS_Data.tail())

# Describe
print("\n--- Describe ---")
display(NPS_Data.describe(include='all'))

# Nulls
print("\n--- Null Values ---")
null_counts = NPS_Data.isnull().sum()
null_pct = (NPS_Data.isnull().sum() / len(NPS_Data)) * 100
null_df = pd.DataFrame({'Count': null_counts, 'Percentage': null_pct})
null_df = null_df[null_df['Count'] > 0].sort_values('Count', ascending=False)
if len(null_df) > 0:
    display(null_df)
else:
    print("No null values found")

# Uniques
print("\n--- Unique Values per Column ---")
unique_counts = NPS_Data.nunique().sort_values()
display(pd.DataFrame({'Unique': unique_counts}))

============================================================
DataFrame: NPS_Data
============================================================

Shape: 4,129 rows, 17 columns

--- Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4129 entries, 0 to 4128
Data columns (total 17 columns):
 #   Column                                                                                                                 Non-Null Count  Dtype
---  ------                                                                                                                 --------------  -----
 0   Submission ID                                                                                                          4129 non-null   object
 1   Respondent ID                                                                                                          4129 non-null   object
 2   Submitted at                                                                                                           4129 non-null   datetime64[ns]
 3   Loan Id                                                                                                                4129 non-null   object
 4   Using a scale from 0 (not likely) to 10 (very likely), how likely are you to recommend MoPhones to friends or family?  3985 non-null   float64
 5   What is the main reason for your score?                                                                                1183 non-null   object
 6   What is one thing we could do to improve your experience with us?                                                      1134 non-null   object
 7   Are you happy with the quality and performance of your MoPhones device?                                                2627 non-null   object
 8   Are you happy with the service and support provided by MoPhones?                                                       2608 non-null   object
 9   Have you ever experienced a delay in your payment reflecting in your Mophones account?                                 2369 non-null   object
 10  Have you ever had difficulty getting assistance from MoPhones customer support when needed?                            2352 non-null   object
 11  (If Yes) – Please describe the challenge you faced and how we can improve your experience.                             1961 non-null   object
 12  Have you experienced any battery-related issues with your MoPhones device?                                             2081 non-null   object
 13  Have you used the MoPhones app (MoApp) to manage your account or make payments?                                        2060 non-null   object
 14  Which communication channel do you prefer when contacting MoPhones for inquiries or support?                           2037 non-null   object
 15  Have you ever had your phone lock despite making a payment on time?                                                    2030 non-null   object
 16  Any other Feedback?                                                                                                    1753 non-null   object
dtypes: datetime64[ns](1), float64(1), object(15)
memory usage: 548.5+ KB

--- Head (5 rows) ---

,Submission ID,Respondent ID,Submitted at,Loan Id,"Using a scale from 0 (not likely) to 10 (very likely), how likely are you to recommend MoPhones to friends or family?",What is the main reason for your score?,What is one thing we could do to improve your experience with us?,Are you happy with the quality and performance of your MoPhones device?,Are you happy with the service and support provided by MoPhones?,Have you ever experienced a delay in your payment reflecting in your Mophones account?,Have you ever had difficulty getting assistance from MoPhones customer support when needed?,(If Yes) – Please describe the challenge you faced and how we can improve your experience.,Have you experienced any battery-related issues with your MoPhones device?,Have you used the MoPhones app (MoApp) to manage your account or make payments?,Which communication channel do you prefer when contacting MoPhones for inquiries or support?,Have you ever had your phone lock despite making a payment on time?,Any other Feedback?
0,BzK4Q11,k4z1Y6,2025-04-22 15:15:00,rec2FCxHhqXw6aKRU,6.0,NaN,NaN,Yes,Yes,Yes,Yes,Unlocking my phone,No,"Yes, and I am satisfied with the MoApp",MoPhones App,Yes,NaN
1,b59V45Z,AY9GMk,2025-04-22 15:18:00,recQcLWbPcep18Wdw,10.0,NaN,NaN,Yes,Yes,No,No,Response team always on time,No,"Yes, and I am satisfied with the MoApp",Free SMS – 25044,No,Would like to upgrade once I'm done with this ...
2,GxKvYKO,eGz8Ek,2025-04-22 15:31:00,recei9UEU0e5F9HuG,5.0,NaN,NaN,No,No,No,Yes,I bought a Samsung A42 which has fingerprint l...,No,"Yes, and I am satisfied with the MoApp",Phone Call – +254 728 444 442 or +254 709 924 404,Yes,Good service and efficient response
3,A7KP49z,LjOx7j,2025-04-22 15:40:00,recosDWAJvWzAKgLv,1.0,NaN,NaN,No,No,Yes,Yes,Delays,Yes,"Yes, but I am not satisfied with the MoApp",NaN,NaN,NaN
4,81zo6pr,7YE0RR,2025-04-22 15:40:00,recTJng0Mj0dJP1kv,1.0,NaN,NaN,No,No,Yes,Yes,Not satisfied with my phone,Yes,"Yes, but I am not satisfied with the MoApp",MoPhones App,Yes,Not satisfied with my phone

--- Tail (5 rows) ---

,Submission ID,Respondent ID,Submitted at,Loan Id,"Using a scale from 0 (not likely) to 10 (very likely), how likely are you to recommend MoPhones to friends or family?",What is the main reason for your score?,What is one thing we could do to improve your experience with us?,Are you happy with the quality and performance of your MoPhones device?,Are you happy with the service and support provided by MoPhones?,Have you ever experienced a delay in your payment reflecting in your Mophones account?,Have you ever had difficulty getting assistance from MoPhones customer support when needed?,(If Yes) – Please describe the challenge you faced and how we can improve your experience.,Have you experienced any battery-related issues with your MoPhones device?,Have you used the MoPhones app (MoApp) to manage your account or make payments?,Which communication channel do you prefer when contacting MoPhones for inquiries or support?,Have you ever had your phone lock despite making a payment on time?,Any other Feedback?
4124,7R0XpWz,KYxJ2l7,2025-12-22 06:27:00,recOWeFSlZI54IBo7,10.0,It is awesome,Allow installation from other sources...admin ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4125,q4QdM7Y,pbOxobJ,2025-12-23 19:44:00,rec0NSEyy825H22np,0.0,You normally don't solve clients issues you ju...,Those who are in charge of repairs to stop laz...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4126,aQJZ6qX,EkWdgoL,2025-12-26 04:17:00,recDLiUM5pL83cccH,4.0,Sometimes my mpesa doesn't work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4127,QK8RME8,BPOMzK,2025-12-26 21:42:00,reclnYf4d3hlACa2X,8.0,Customer service,Customer service takes,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4128,q4QvEg8,EkWW0v2,2025-12-27 02:06:00,recEB6LXVzcqlim1p,10.0,I am using a MoPhone and for sure it was a goo...,"So far soo good, my process was pretty seamless.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Describe ---

,Submission ID,Respondent ID,Submitted at,Loan Id,"Using a scale from 0 (not likely) to 10 (very likely), how likely are you to recommend MoPhones to friends or family?",What is the main reason for your score?,What is one thing we could do to improve your experience with us?,Are you happy with the quality and performance of your MoPhones device?,Are you happy with the service and support provided by MoPhones?,Have you ever experienced a delay in your payment reflecting in your Mophones account?,Have you ever had difficulty getting assistance from MoPhones customer support when needed?,(If Yes) – Please describe the challenge you faced and how we can improve your experience.,Have you experienced any battery-related issues with your MoPhones device?,Have you used the MoPhones app (MoApp) to manage your account or make payments?,Which communication channel do you prefer when contacting MoPhones for inquiries or support?,Have you ever had your phone lock despite making a payment on time?,Any other Feedback?
count,4129,4129,4129,4129,3985.000000,1183,1134,2627,2608,2369,2352,1961,2081,2060,2037,2030,1753
unique,4129,3756,NaN,3532,NaN,1060,1068,2,2,2,3,1340,2,3,5,2,1163
top,BzK4Q11,0NoGJ6,NaN,recUuLe9KNHZD6Mql,NaN,Good service,Nothing,Yes,Yes,No,No,No,No,"Yes, and I am satisfied with the MoApp",Phone Call – +254 728 444 442 or +254 709 924 404,No,No
freq,1,4,NaN,5,NaN,23,13,1999,2037,1647,1460,313,1293,1419,1046,1467,354
mean,NaN,NaN,2025-08-29 20:39:40.324533760,NaN,6.779172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,2025-04-22 15:15:00,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,2025-07-17 17:16:00,NaN,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,2025-08-29 03:35:00,NaN,8.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,2025-10-08 08:46:00,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,2025-12-27 02:06:00,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,3.386783,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Null Values ---

                                                    Count  Percentage
What is one thing we could do to improve your e...   2995   72.535723
What is the main reason for your score?              2946   71.348995
Any other Feedback?                                  2376   57.544200
(If Yes) – Please describe the challenge you fa...   2168   52.506660
Have you ever had your phone lock despite makin...   2099   50.835553
Which communication channel do you prefer when ...   2092   50.666021
Have you used the MoPhones app (MoApp) to manag...   2069   50.108985
Have you experienced any battery-related issues...   2048   49.600388
Have you ever had difficulty getting assistance...   1777   43.037055
Have you ever experienced a delay in your payme...   1760   42.625333
Are you happy with the service and support prov...   1521   36.837007
Are you happy with the quality and performance ...   1502   36.376847
Using a scale from 0 (not likely) to 10 (very l...    144    3.487527

--- Unique Values per Column ---

                                                    Unique
Are you happy with the service and support prov...       2
Have you experienced any battery-related issues...       2
Are you happy with the quality and performance ...       2
Have you ever had your phone lock despite makin...       2
Have you ever experienced a delay in your payme...       2
Have you used the MoPhones app (MoApp) to manag...       3
Have you ever had difficulty getting assistance...       3
Which communication channel do you prefer when ...       5
Using a scale from 0 (not likely) to 10 (very l...      11
What is the main reason for your score?               1060
What is one thing we could do to improve your e...    1068
Any other Feedback?                                   1163
(If Yes) – Please describe the challenge you fa...    1340
Submitted at                                          3087
Loan Id                                               3532
Respondent ID                                         3756
Submission ID                                         4129

In [18]:
# Profile: Sales_and_Customer_Data_Sales_Details
print("\n" + "="*60)
print("DataFrame: Sales_and_Customer_Data_Sales_Details")
print("="*60)

# Shape
print(f"\nShape: {Sales_and_Customer_Data_Sales_Details.shape[0]:,} rows, {Sales_and_Customer_Data_Sales_Details.shape[1]:,} columns")

# Info
print("\n--- Info ---")
Sales_and_Customer_Data_Sales_Details.info()

# Head
print("\n--- Head (5 rows) ---")
display(Sales_and_Customer_Data_Sales_Details.head())

# Tail  
print("\n--- Tail (5 rows) ---")
display(Sales_and_Customer_Data_Sales_Details.tail())

# Describe
print("\n--- Describe ---")
display(Sales_and_Customer_Data_Sales_Details.describe(include='all'))

# Nulls
print("\n--- Null Values ---")
null_counts = Sales_and_Customer_Data_Sales_Details.isnull().sum()
null_pct = (Sales_and_Customer_Data_Sales_Details.isnull().sum() / len(Sales_and_Customer_Data_Sales_Details)) * 100
null_df = pd.DataFrame({'Count': null_counts, 'Percentage': null_pct})
null_df = null_df[null_df['Count'] > 0].sort_values('Count', ascending=False)
if len(null_df) > 0:
    display(null_df)
else:
    print("No null values found")

# Uniques
print("\n--- Unique Values per Column ---")
unique_counts = Sales_and_Customer_Data_Sales_Details.nunique().sort_values()
display(pd.DataFrame({'Unique': unique_counts}))

============================================================
DataFrame: Sales_and_Customer_Data_Sales_Details
============================================================

Shape: 1,048,575 rows, 16 columns

--- Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   SALE_ID                   20747 non-null  object
 1   SALE_DATE                 20747 non-null  datetime64[ns]
 2   RETURNED                  20747 non-null  float64
 3   RETURN_DATE               1744 non-null   datetime64[ns]
 4   SALE_TYPE                 20745 non-null  object
 5   SELLER                    20670 non-null  object
 6   SELLER_TYPE               15776 non-null  object
 7   RETURN_POLICY_COMPLIANCE  1744 non-null   object
 8   CASH_PRICE                20745 non-null  float64
 9   LOAN_PRICE                20745 non-null  float64
 10  CLIENT_MODEL              20722 non-null  object
 11  BUSINESS_MODEL            20747 non-null  object
 12  LOAN_TERM                 20743 non-null  object
 13  PRODUCT_NAME              20745 non-null  object
 14  MODEL                     20745 non-null  object
 15  Loan Id                   20696 non-null  object
dtypes: datetime64[ns](2), float64(3), object(11)
memory usage: 128.0+ MB

--- Head (5 rows) ---

,SALE_ID,SALE_DATE,RETURNED,RETURN_DATE,SALE_TYPE,SELLER,SELLER_TYPE,RETURN_POLICY_COMPLIANCE,CASH_PRICE,LOAN_PRICE,CLIENT_MODEL,BUSINESS_MODEL,LOAN_TERM,PRODUCT_NAME,MODEL,Loan Id
0,recg9SxxjvTdgP6NC,2025-06-26,0.0,NaT,Financed,angela Muthini,Sales Executive,NaN,34999.0,62779.0,1C,1P1C,12M,Samsung-Note-20-128GB,Note-20,recg9SxxjvTdgP6NC
1,rec0P2Z778n8igV9u,2024-07-15,0.0,NaT,Financed,Divinah Kerubo Nyangenyo,Sales Executive,NaN,99499.0,157139.0,1C,1P1C,12M,Samsung-Galaxy-S22-Ultra-256GB,Galaxy-S22-Ultra,rec0P2Z778n8igV9u
2,recbZfItLLouuJj9h,2024-08-15,0.0,NaT,Financed,Cynthia Mutai,Sales Executive,NaN,32999.0,51259.0,1C,3P1C,12M,Samsung-Galaxy-A15-128GB,Galaxy-A15,recbZfItLLouuJj9h
3,recBtxgmMbuLKdANY,2023-05-05,0.0,NaT,Financed,Simon Ojiambo,NaN,NaN,38499.0,63159.0,1C,1P1C,12M,Samsung-Galaxy-S10-128GB,Galaxy-S10,recBtxgmMbuLKdANY
4,recspqipYdXTH1lNV,2025-07-14,0.0,NaT,Financed,Esther Nduta,NaN,NaN,116999.0,187239.0,3C,3P3C,3M,Samsung-Galaxy-S24-Ultra-512GB,Galaxy-S24-Ultra,recspqipYdXTH1lNV

--- Tail (5 rows) ---

,SALE_ID,SALE_DATE,RETURNED,RETURN_DATE,SALE_TYPE,SELLER,SELLER_TYPE,RETURN_POLICY_COMPLIANCE,CASH_PRICE,LOAN_PRICE,CLIENT_MODEL,BUSINESS_MODEL,LOAN_TERM,PRODUCT_NAME,MODEL,Loan Id
1048570,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048571,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048572,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048573,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048574,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Describe ---

,SALE_ID,SALE_DATE,RETURNED,RETURN_DATE,SALE_TYPE,SELLER,SELLER_TYPE,RETURN_POLICY_COMPLIANCE,CASH_PRICE,LOAN_PRICE,CLIENT_MODEL,BUSINESS_MODEL,LOAN_TERM,PRODUCT_NAME,MODEL,Loan Id
count,20747,20747,20747.000000,1744,20745,20670,15776,1744,20745.000000,20745.000000,20722,20747,20743,20745,20745,20696
unique,20747,NaN,NaN,NaN,3,519,5,2,NaN,NaN,3,7,3,132,82,20691
top,recg9SxxjvTdgP6NC,NaN,NaN,NaN,Financed,Christine Muloko,Sales Executive,out of policy,NaN,NaN,1C,1P1C,12M,Samsung-Note-10-Plus-256GB,Note-10-Plus,rec1s8Oc6qhMCGKZ2
freq,1,NaN,NaN,NaN,19570,1295,10517,1260,NaN,NaN,16099,12721,19418,1953,1985,2
mean,NaN,2025-01-24 01:12:23.529184768,0.084012,2025-03-11 20:26:08.807339520,NaN,NaN,NaN,NaN,42392.583852,73090.441465,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,2023-02-08 00:00:00,0.000000,2023-03-16 00:00:00,NaN,NaN,NaN,NaN,7999.000000,15159.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,2024-07-25 00:00:00,0.000000,2024-10-16 00:00:00,NaN,NaN,NaN,NaN,29999.000000,51259.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,2025-03-06 00:00:00,0.000000,2025-04-07 00:00:00,NaN,NaN,NaN,NaN,37999.000000,67199.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,2025-08-21 00:00:00,0.000000,2025-08-25 00:00:00,NaN,NaN,NaN,NaN,47999.000000,82009.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,2025-12-29 00:00:00,1.000000,2025-12-29 00:00:00,NaN,NaN,NaN,NaN,215499.000000,334219.000000,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,0.277413,NaN,NaN,NaN,NaN,NaN,19082.531473,31220.699129,NaN,NaN,NaN,NaN,NaN,NaN

--- Null Values ---

                            Count  Percentage
RETURN_DATE               1046831   99.833679
RETURN_POLICY_COMPLIANCE  1046831   99.833679
SELLER_TYPE               1032799   98.495482
SELLER                    1027905   98.028753
Loan Id                   1027879   98.026274
CLIENT_MODEL              1027853   98.023794
LOAN_TERM                 1027832   98.021791
SALE_TYPE                 1027830   98.021601
CASH_PRICE                1027830   98.021601
LOAN_PRICE                1027830   98.021601
PRODUCT_NAME              1027830   98.021601
MODEL                     1027830   98.021601
SALE_ID                   1027828   98.021410
SALE_DATE                 1027828   98.021410
RETURNED                  1027828   98.021410
BUSINESS_MODEL            1027828   98.021410

--- Unique Values per Column ---

                          Unique
RETURNED                       2
RETURN_POLICY_COMPLIANCE       2
SALE_TYPE                      3
CLIENT_MODEL                   3
LOAN_TERM                      3
SELLER_TYPE                    5
BUSINESS_MODEL                 7
MODEL                         82
PRODUCT_NAME                 132
CASH_PRICE                   259
SELLER                       519
RETURN_DATE                  530
LOAN_PRICE                   930
SALE_DATE                    939
Loan Id                    20691
SALE_ID                    20747

In [19]:
# Profile: Sales_and_Customer_Data_Gender
print("\n" + "="*60)
print("DataFrame: Sales_and_Customer_Data_Gender")
print("="*60)

# Shape
print(f"\nShape: {Sales_and_Customer_Data_Gender.shape[0]:,} rows, {Sales_and_Customer_Data_Gender.shape[1]:,} columns")

# Info
print("\n--- Info ---")
Sales_and_Customer_Data_Gender.info()

# Head
print("\n--- Head (5 rows) ---")
display(Sales_and_Customer_Data_Gender.head())

# Tail  
print("\n--- Tail (5 rows) ---")
display(Sales_and_Customer_Data_Gender.tail())

# Describe
print("\n--- Describe ---")
display(Sales_and_Customer_Data_Gender.describe(include='all'))

# Nulls
print("\n--- Null Values ---")
null_counts = Sales_and_Customer_Data_Gender.isnull().sum()
null_pct = (Sales_and_Customer_Data_Gender.isnull().sum() / len(Sales_and_Customer_Data_Gender)) * 100
null_df = pd.DataFrame({'Count': null_counts, 'Percentage': null_pct})
null_df = null_df[null_df['Count'] > 0].sort_values('Count', ascending=False)
if len(null_df) > 0:
    display(null_df)
else:
    print("No null values found")

# Uniques
print("\n--- Unique Values per Column ---")
unique_counts = Sales_and_Customer_Data_Gender.nunique().sort_values()
display(pd.DataFrame({'Unique': unique_counts}))

============================================================
DataFrame: Sales_and_Customer_Data_Gender
============================================================

Shape: 1,048,575 rows, 3 columns

--- Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Loan Id      14896 non-null  object
 1   Citizenship  49788 non-null  object
 2   Gender       49783 non-null  object
dtypes: object(3)
memory usage: 24.0+ MB

--- Head (5 rows) ---

  Loan Id Citizenship  Gender
0     NaN      KENYAN  Female
1     NaN      KENYAN    Male
2     NaN      KENYAN    Male
3     NaN      KENYAN    Male
4     NaN      KENYAN  Female

--- Tail (5 rows) ---

        Loan Id Citizenship Gender
1048570     NaN         NaN    NaN
1048571     NaN         NaN    NaN
1048572     NaN         NaN    NaN
1048573     NaN         NaN    NaN
1048574     NaN         NaN    NaN

--- Describe ---

                  Loan Id Citizenship Gender
count               14896       49788  49783
unique              10497           3      5
top     recDXYKagrTFQRY6N      KENYAN   Male
freq                   35       46075  31329

--- Null Values ---

               Count  Percentage
Loan Id      1033679   98.579405
Gender        998792   95.252319
Citizenship   998787   95.251842

--- Unique Values per Column ---

             Unique
Citizenship       3
Gender            5
Loan Id       10497

In [20]:
# Profile: Sales_and_Customer_Data_DOB
print("\n" + "="*60)
print("DataFrame: Sales_and_Customer_Data_DOB")
print("="*60)

# Shape
print(f"\nShape: {Sales_and_Customer_Data_DOB.shape[0]:,} rows, {Sales_and_Customer_Data_DOB.shape[1]:,} columns")

# Info
print("\n--- Info ---")
Sales_and_Customer_Data_DOB.info()

# Head
print("\n--- Head (5 rows) ---")
display(Sales_and_Customer_Data_DOB.head())

# Tail  
print("\n--- Tail (5 rows) ---")
display(Sales_and_Customer_Data_DOB.tail())

# Describe
print("\n--- Describe ---")
display(Sales_and_Customer_Data_DOB.describe(include='all'))

# Nulls
print("\n--- Null Values ---")
null_counts = Sales_and_Customer_Data_DOB.isnull().sum()
null_pct = (Sales_and_Customer_Data_DOB.isnull().sum() / len(Sales_and_Customer_Data_DOB)) * 100
null_df = pd.DataFrame({'Count': null_counts, 'Percentage': null_pct})
null_df = null_df[null_df['Count'] > 0].sort_values('Count', ascending=False)
if len(null_df) > 0:
    display(null_df)
else:
    print("No null values found")

# Uniques
print("\n--- Unique Values per Column ---")
unique_counts = Sales_and_Customer_Data_DOB.nunique().sort_values()
display(pd.DataFrame({'Unique': unique_counts}))

============================================================
DataFrame: Sales_and_Customer_Data_DOB
============================================================

Shape: 1,048,575 rows, 5 columns

--- Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   _id            57130 non-null  object
 1   provider       57130 non-null  object
 2   date_of_birth  56921 non-null  object
 3   Loan Id        13562 non-null  object
 4   createdAt UTC  57130 non-null  object
dtypes: object(5)
memory usage: 40.0+ MB

--- Head (5 rows) ---

,_id,provider,date_of_birth,Loan Id,createdAt UTC
0,67c57f7b5a877e67ca1e9636,TRANSUNION,1992-01-15T00:00:00+03:00,recB62iDqCzZRSLvJ,2025-03-03T12:12:02.196Z
1,67c57f7c5a877e67ca1e964f,TRANSUNION,2002-04-13T00:00:00+03:00,recYkhiMo3z86wqq8,2025-03-03T12:12:02.967Z
2,67c585175a877e67ca1e99eb,TRANSUNION,1991-05-17T00:00:00+03:00,recVJkba3KsQiPdQ0,2025-03-03T10:32:05.687Z
3,67c585185a877e67ca1e9a00,TRANSUNION,1969-01-01T00:00:00+03:00,NaN,2025-03-03T10:32:06.385Z
4,67c593465a877e67ca1e9c4d,TRANSUNION,2000-10-28T00:00:00+03:00,NaN,2025-03-03T11:47:15.558Z

--- Tail (5 rows) ---

         _id provider date_of_birth Loan Id  createdAt UTC
1048570  NaN      NaN           NaN      NaN           NaN
1048571  NaN      NaN           NaN      NaN           NaN
1048572  NaN      NaN           NaN      NaN           NaN
1048573  NaN      NaN           NaN      NaN           NaN
1048574  NaN      NaN           NaN      NaN           NaN

--- Describe ---

,_id,provider,date_of_birth,Loan Id,createdAt UTC
count,57130,57130,56921,13562,57130
unique,57130,3,17087,11217,57130
top,67c57f7b5a877e67ca1e9636,SPINMOBILE,1970-01-01T00:00:00+03:00,recDXYKagrTFQRY6N,2025-03-03T12:12:02.196Z
freq,1,39244,193,36,1

--- Null Values ---

                 Count  Percentage
Loan Id        1035013   98.706626
date_of_birth   991654   94.571585
_id             991445   94.551653
provider        991445   94.551653
createdAt UTC   991445   94.551653

--- Unique Values per Column ---

               Unique
provider            3
Loan Id         11217
date_of_birth   17087
_id             57130
createdAt UTC   57130

In [21]:
# Profile: Sales_and_Customer_Data_Income_Level
print("\n" + "="*60)
print("DataFrame: Sales_and_Customer_Data_Income_Level")
print("="*60)

# Shape
print(f"\nShape: {Sales_and_Customer_Data_Income_Level.shape[0]:,} rows, {Sales_and_Customer_Data_Income_Level.shape[1]:,} columns")

# Info
print("\n--- Info ---")
Sales_and_Customer_Data_Income_Level.info()

# Head
print("\n--- Head (5 rows) ---")
display(Sales_and_Customer_Data_Income_Level.head())

# Tail  
print("\n--- Tail (5 rows) ---")
display(Sales_and_Customer_Data_Income_Level.tail())

# Describe
print("\n--- Describe ---")
display(Sales_and_Customer_Data_Income_Level.describe(include='all'))

# Nulls
print("\n--- Null Values ---")
null_counts = Sales_and_Customer_Data_Income_Level.isnull().sum()
null_pct = (Sales_and_Customer_Data_Income_Level.isnull().sum() / len(Sales_and_Customer_Data_Income_Level)) * 100
null_df = pd.DataFrame({'Count': null_counts, 'Percentage': null_pct})
null_df = null_df[null_df['Count'] > 0].sort_values('Count', ascending=False)
if len(null_df) > 0:
    display(null_df)
else:
    print("No null values found")

# Uniques
print("\n--- Unique Values per Column ---")
unique_counts = Sales_and_Customer_Data_Income_Level.nunique().sort_values()
display(pd.DataFrame({'Unique': unique_counts}))

============================================================
DataFrame: Sales_and_Customer_Data_Income_Level
============================================================

Shape: 1,048,575 rows, 6 columns

--- Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Loan Id                      11885 non-null  object
 1   Duration                     22839 non-null  float64
 2   Received                     22839 non-null  float64
 3   Persons Received From Total  22839 non-null  float64
 4   Banks Received               22839 non-null  float64
 5   Paybills Received Others     22839 non-null  float64
dtypes: float64(5), object(1)
memory usage: 48.0+ MB

--- Head (5 rows) ---

,Loan Id,Duration,Received,Persons Received From Total,Banks Received,Paybills Received Others
0,NaN,12.0,203934.19,203278.0,100.0,120.0
1,NaN,12.0,1153225.00,1153135.0,772564.0,150.0
2,NaN,12.0,130521.82,129012.0,0.0,2467.0
3,NaN,10.0,1312886.29,890484.0,6072623.0,210110.0
4,NaN,6.0,237982.00,237982.0,44829.0,18564.0

--- Tail (5 rows) ---

,Loan Id,Duration,Received,Persons Received From Total,Banks Received,Paybills Received Others
1048570,NaN,NaN,NaN,NaN,NaN,NaN
1048571,NaN,NaN,NaN,NaN,NaN,NaN
1048572,NaN,NaN,NaN,NaN,NaN,NaN
1048573,NaN,NaN,NaN,NaN,NaN,NaN
1048574,NaN,NaN,NaN,NaN,NaN,NaN

--- Describe ---

,Loan Id,Duration,Received,Persons Received From Total,Banks Received,Paybills Received Others
count,11885,22839.000000,2.283900e+04,2.283900e+04,2.283900e+04,2.283900e+04
unique,10609,NaN,NaN,NaN,NaN,NaN
top,rec7jCmNMPNWJHeDs,NaN,NaN,NaN,NaN,NaN
freq,11,NaN,NaN,NaN,NaN,NaN
mean,NaN,8.572135,7.005648e+05,6.257232e+05,3.495485e+05,9.228903e+04
std,NaN,3.090052,1.315134e+06,1.206708e+06,9.508558e+05,4.583737e+05
min,NaN,1.000000,0.000000e+00,0.000000e+00,0.000000e+00,-1.975599e+06
25%,NaN,6.000000,1.392970e+05,1.221155e+05,1.784500e+04,4.250000e+02
50%,NaN,6.000000,3.240326e+05,2.864700e+05,8.648000e+04,6.851700e+03
75%,NaN,12.000000,7.545676e+05,6.776180e+05,2.904700e+05,4.749500e+04
max,NaN,24.000000,3.827115e+07,3.789568e+07,2.607615e+07,2.200725e+07

--- Null Values ---

                               Count  Percentage
Loan Id                      1036690   98.866557
Duration                     1025736   97.821901
Received                     1025736   97.821901
Persons Received From Total  1025736   97.821901
Banks Received               1025736   97.821901
Paybills Received Others     1025736   97.821901

--- Unique Values per Column ---

                             Unique
Duration                         23
Loan Id                       10609
Paybills Received Others      12560
Banks Received                16632
Persons Received From Total   20993
Received                      21191